// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `address` field of a record.
struct AddressField {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using AddressFieldLib for AddressField global;

/// @notice The `address` field codec, shared by every `address` field of every table.
library AddressFieldLib {
  function load(AddressField memory self) internal view returns (address) {
    return address(uint160(bytes20(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(AddressField memory self, address value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(address value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (address) {
    return address(uint160(Bytes.getBytes20(staticData, offset)));
  }
}
