// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { EncodedLengths } from "../../EncodedLengths.sol";
import { SliceLib } from "../../Slice.sol";
import { EncodeArray } from "../../tightcoder/EncodeArray.sol";
import { DynamicRange } from "./_dynamic.sol";

/// @notice A handle to one `bool[]` field of a record.
struct BoolArrayField {
  Record record;
  uint8 dynamicIndex;
}

using BoolArrayFieldLib for BoolArrayField global;

/// @notice The `bool[]` field codec, shared by every `bool[]` field of every table.
library BoolArrayFieldLib {
  uint256 constant _ELEMENT_SIZE = 1;

  function load(BoolArrayField memory self) internal view returns (bool[] memory) {
    bytes memory blob = StoreAccess.getDynamicField(self.record, self.dynamicIndex);
    return SliceLib.getSubslice(blob, 0, blob.length).decodeArray_bool();
  }

  function save(BoolArrayField memory self, bool[] memory value) internal {
    StoreAccess.setDynamicField(self.record, self.dynamicIndex, EncodeArray.encode(value));
  }

  /// @notice Number of elements.
  function length(BoolArrayField memory self) internal view returns (uint256) {
    return StoreAccess.getDynamicFieldLength(self.record, self.dynamicIndex) / _ELEMENT_SIZE;
  }

  /// @notice Load one element by index.
  function load(BoolArrayField memory self, uint256 index) internal view returns (bool) {
    bytes memory blob = StoreAccess.getDynamicFieldSlice(
      self.record,
      self.dynamicIndex,
      index * _ELEMENT_SIZE,
      (index + 1) * _ELEMENT_SIZE
    );
    return uint8(bytes1(blob)) != 0;
  }

  /// @notice Overwrite one element by index.
  function save(BoolArrayField memory self, uint256 index, bool element) internal {
    StoreAccess.spliceDynamicData(
      self.record,
      self.dynamicIndex,
      uint40(index * _ELEMENT_SIZE),
      uint40(_ELEMENT_SIZE),
      abi.encodePacked(element)
    );
  }

  function push(BoolArrayField memory self, bool element) internal {
    StoreAccess.pushToDynamicField(self.record, self.dynamicIndex, abi.encodePacked(element));
  }

  function pop(BoolArrayField memory self) internal {
    StoreAccess.popFromDynamicField(self.record, self.dynamicIndex, _ELEMENT_SIZE);
  }

  function encode(bool[] memory value) internal pure returns (bytes memory) {
    return EncodeArray.encode(value);
  }

  function byteLength(bool[] memory value) internal pure returns (uint256) {
    return value.length * _ELEMENT_SIZE;
  }

  function decode(
    bytes memory dynamicData,
    EncodedLengths encodedLengths,
    uint8 dynamicIndex
  ) internal pure returns (bool[] memory) {
    (uint256 start, uint256 end) = DynamicRange.range(encodedLengths, dynamicIndex);
    return SliceLib.getSubslice(dynamicData, start, end).decodeArray_bool();
  }
}
