// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `bytes25` field of a record.
struct Bytes25Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes25FieldLib for Bytes25Field global;

/// @notice The `bytes25` field codec, shared by every `bytes25` field of every table.
library Bytes25FieldLib {
  function load(Bytes25Field memory self) internal view returns (bytes25) {
    return bytes25(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes25Field memory self, bytes25 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes25 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes25) {
    return Bytes.getBytes25(staticData, offset);
  }
}
