// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `bytes14` field of a record.
struct Bytes14Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes14FieldLib for Bytes14Field global;

/// @notice The `bytes14` field codec, shared by every `bytes14` field of every table.
library Bytes14FieldLib {
  function load(Bytes14Field memory self) internal view returns (bytes14) {
    return bytes14(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes14Field memory self, bytes14 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes14 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes14) {
    return Bytes.getBytes14(staticData, offset);
  }
}
