// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `bytes23` field of a record.
struct Bytes23Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes23FieldLib for Bytes23Field global;

/// @notice The `bytes23` field codec, shared by every `bytes23` field of every table.
library Bytes23FieldLib {
  function load(Bytes23Field memory self) internal view returns (bytes23) {
    return bytes23(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes23Field memory self, bytes23 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes23 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes23) {
    return Bytes.getBytes23(staticData, offset);
  }
}
