// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `bytes29` field of a record.
struct Bytes29Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes29FieldLib for Bytes29Field global;

/// @notice The `bytes29` field codec, shared by every `bytes29` field of every table.
library Bytes29FieldLib {
  function load(Bytes29Field memory self) internal view returns (bytes29) {
    return bytes29(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes29Field memory self, bytes29 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes29 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes29) {
    return Bytes.getBytes29(staticData, offset);
  }
}
