// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `bytes21` field of a record.
struct Bytes21Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes21FieldLib for Bytes21Field global;

/// @notice The `bytes21` field codec, shared by every `bytes21` field of every table.
library Bytes21FieldLib {
  function load(Bytes21Field memory self) internal view returns (bytes21) {
    return bytes21(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes21Field memory self, bytes21 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes21 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes21) {
    return Bytes.getBytes21(staticData, offset);
  }
}
