// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `bytes30` field of a record.
struct Bytes30Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes30FieldLib for Bytes30Field global;

/// @notice The `bytes30` field codec, shared by every `bytes30` field of every table.
library Bytes30FieldLib {
  function load(Bytes30Field memory self) internal view returns (bytes30) {
    return bytes30(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes30Field memory self, bytes30 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes30 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes30) {
    return Bytes.getBytes30(staticData, offset);
  }
}
