// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `bytes28` field of a record.
struct Bytes28Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes28FieldLib for Bytes28Field global;

/// @notice The `bytes28` field codec, shared by every `bytes28` field of every table.
library Bytes28FieldLib {
  function load(Bytes28Field memory self) internal view returns (bytes28) {
    return bytes28(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes28Field memory self, bytes28 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes28 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes28) {
    return Bytes.getBytes28(staticData, offset);
  }
}
