// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `bytes17` field of a record.
struct Bytes17Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes17FieldLib for Bytes17Field global;

/// @notice The `bytes17` field codec, shared by every `bytes17` field of every table.
library Bytes17FieldLib {
  function load(Bytes17Field memory self) internal view returns (bytes17) {
    return bytes17(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes17Field memory self, bytes17 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes17 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes17) {
    return Bytes.getBytes17(staticData, offset);
  }
}
