// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `bytes15` field of a record.
struct Bytes15Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes15FieldLib for Bytes15Field global;

/// @notice The `bytes15` field codec, shared by every `bytes15` field of every table.
library Bytes15FieldLib {
  function load(Bytes15Field memory self) internal view returns (bytes15) {
    return bytes15(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes15Field memory self, bytes15 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes15 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes15) {
    return Bytes.getBytes15(staticData, offset);
  }
}
