// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `bytes7` field of a record.
struct Bytes7Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes7FieldLib for Bytes7Field global;

/// @notice The `bytes7` field codec, shared by every `bytes7` field of every table.
library Bytes7FieldLib {
  function load(Bytes7Field memory self) internal view returns (bytes7) {
    return bytes7(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes7Field memory self, bytes7 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes7 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes7) {
    return Bytes.getBytes7(staticData, offset);
  }
}
