// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { EncodedLengths } from "../../EncodedLengths.sol";
import { SliceLib } from "../../Slice.sol";
import { EncodeArray } from "../../tightcoder/EncodeArray.sol";
import { DynamicRange } from "./_dynamic.sol";

/// @notice A handle to one `bytes27[]` field of a record.
struct Bytes27ArrayField {
  Record record;
  uint8 dynamicIndex;
}

using Bytes27ArrayFieldLib for Bytes27ArrayField global;

/// @notice The `bytes27[]` field codec, shared by every `bytes27[]` field of every table.
library Bytes27ArrayFieldLib {
  uint256 constant _ELEMENT_SIZE = 27;

  function load(Bytes27ArrayField memory self) internal view returns (bytes27[] memory) {
    bytes memory blob = StoreAccess.getDynamicField(self.record, self.dynamicIndex);
    return SliceLib.getSubslice(blob, 0, blob.length).decodeArray_bytes27();
  }

  function save(Bytes27ArrayField memory self, bytes27[] memory value) internal {
    StoreAccess.setDynamicField(self.record, self.dynamicIndex, EncodeArray.encode(value));
  }

  /// @notice Number of elements.
  function length(Bytes27ArrayField memory self) internal view returns (uint256) {
    return StoreAccess.getDynamicFieldLength(self.record, self.dynamicIndex) / _ELEMENT_SIZE;
  }

  /// @notice Load one element by index.
  function load(Bytes27ArrayField memory self, uint256 index) internal view returns (bytes27) {
    bytes memory blob = StoreAccess.getDynamicFieldSlice(
      self.record,
      self.dynamicIndex,
      index * _ELEMENT_SIZE,
      (index + 1) * _ELEMENT_SIZE
    );
    return bytes27(blob);
  }

  /// @notice Overwrite one element by index.
  function save(Bytes27ArrayField memory self, uint256 index, bytes27 element) internal {
    StoreAccess.spliceDynamicData(
      self.record,
      self.dynamicIndex,
      uint40(index * _ELEMENT_SIZE),
      uint40(_ELEMENT_SIZE),
      abi.encodePacked(element)
    );
  }

  function push(Bytes27ArrayField memory self, bytes27 element) internal {
    StoreAccess.pushToDynamicField(self.record, self.dynamicIndex, abi.encodePacked(element));
  }

  function pop(Bytes27ArrayField memory self) internal {
    StoreAccess.popFromDynamicField(self.record, self.dynamicIndex, _ELEMENT_SIZE);
  }

  function encode(bytes27[] memory value) internal pure returns (bytes memory) {
    return EncodeArray.encode(value);
  }

  function byteLength(bytes27[] memory value) internal pure returns (uint256) {
    return value.length * _ELEMENT_SIZE;
  }

  function decode(
    bytes memory dynamicData,
    EncodedLengths encodedLengths,
    uint8 dynamicIndex
  ) internal pure returns (bytes27[] memory) {
    (uint256 start, uint256 end) = DynamicRange.range(encodedLengths, dynamicIndex);
    return SliceLib.getSubslice(dynamicData, start, end).decodeArray_bytes27();
  }
}
