// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `bytes6` field of a record.
struct Bytes6Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes6FieldLib for Bytes6Field global;

/// @notice The `bytes6` field codec, shared by every `bytes6` field of every table.
library Bytes6FieldLib {
  function load(Bytes6Field memory self) internal view returns (bytes6) {
    return bytes6(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes6Field memory self, bytes6 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes6 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes6) {
    return Bytes.getBytes6(staticData, offset);
  }
}
