// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `bytes1` field of a record.
struct Bytes1Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes1FieldLib for Bytes1Field global;

/// @notice The `bytes1` field codec, shared by every `bytes1` field of every table.
library Bytes1FieldLib {
  function load(Bytes1Field memory self) internal view returns (bytes1) {
    return bytes1(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes1Field memory self, bytes1 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes1 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes1) {
    return Bytes.getBytes1(staticData, offset);
  }
}
