// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { EncodedLengths } from "../../EncodedLengths.sol";
import { SliceLib } from "../../Slice.sol";
import { DynamicRange } from "./_dynamic.sol";

/// @notice A handle to one `bytes` field of a record.
struct BytesField {
  Record record;
  uint8 dynamicIndex;
}

using BytesFieldLib for BytesField global;

/// @notice The `bytes` field codec, shared by every `bytes` field of every table.
library BytesFieldLib {
  function load(BytesField memory self) internal view returns (bytes memory) {
    return StoreAccess.getDynamicField(self.record, self.dynamicIndex);
  }

  function save(BytesField memory self, bytes memory value) internal {
    StoreAccess.setDynamicField(self.record, self.dynamicIndex, bytes(value));
  }

  /// @notice Byte length.
  function length(BytesField memory self) internal view returns (uint256) {
    return StoreAccess.getDynamicFieldLength(self.record, self.dynamicIndex);
  }

  function encode(bytes memory value) internal pure returns (bytes memory) {
    return bytes(value);
  }

  function byteLength(bytes memory value) internal pure returns (uint256) {
    return bytes(value).length;
  }

  function decode(
    bytes memory dynamicData,
    EncodedLengths encodedLengths,
    uint8 dynamicIndex
  ) internal pure returns (bytes memory) {
    (uint256 start, uint256 end) = DynamicRange.range(encodedLengths, dynamicIndex);
    return SliceLib.getSubslice(dynamicData, start, end).toBytes();
  }
}
