// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `bytes32` field of a record.
struct Bytes32Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes32FieldLib for Bytes32Field global;

/// @notice The `bytes32` field codec, shared by every `bytes32` field of every table.
library Bytes32FieldLib {
  function load(Bytes32Field memory self) internal view returns (bytes32) {
    return bytes32(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes32Field memory self, bytes32 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes32 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes32) {
    return Bytes.getBytes32(staticData, offset);
  }
}
