// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `bytes22` field of a record.
struct Bytes22Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes22FieldLib for Bytes22Field global;

/// @notice The `bytes22` field codec, shared by every `bytes22` field of every table.
library Bytes22FieldLib {
  function load(Bytes22Field memory self) internal view returns (bytes22) {
    return bytes22(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes22Field memory self, bytes22 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes22 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes22) {
    return Bytes.getBytes22(staticData, offset);
  }
}
