// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `bytes13` field of a record.
struct Bytes13Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes13FieldLib for Bytes13Field global;

/// @notice The `bytes13` field codec, shared by every `bytes13` field of every table.
library Bytes13FieldLib {
  function load(Bytes13Field memory self) internal view returns (bytes13) {
    return bytes13(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes13Field memory self, bytes13 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes13 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes13) {
    return Bytes.getBytes13(staticData, offset);
  }
}
