// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `bytes16` field of a record.
struct Bytes16Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes16FieldLib for Bytes16Field global;

/// @notice The `bytes16` field codec, shared by every `bytes16` field of every table.
library Bytes16FieldLib {
  function load(Bytes16Field memory self) internal view returns (bytes16) {
    return bytes16(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes16Field memory self, bytes16 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes16 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes16) {
    return Bytes.getBytes16(staticData, offset);
  }
}
