// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `bytes31` field of a record.
struct Bytes31Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes31FieldLib for Bytes31Field global;

/// @notice The `bytes31` field codec, shared by every `bytes31` field of every table.
library Bytes31FieldLib {
  function load(Bytes31Field memory self) internal view returns (bytes31) {
    return bytes31(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes31Field memory self, bytes31 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes31 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes31) {
    return Bytes.getBytes31(staticData, offset);
  }
}
