// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `int104` field of a record.
struct Int104Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int104FieldLib for Int104Field global;

/// @notice The `int104` field codec, shared by every `int104` field of every table.
library Int104FieldLib {
  function load(Int104Field memory self) internal view returns (int104) {
    return int104(uint104(bytes13(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int104Field memory self, int104 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int104 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int104) {
    return int104(uint104(Bytes.getBytes13(staticData, offset)));
  }
}
