// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `int192` field of a record.
struct Int192Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int192FieldLib for Int192Field global;

/// @notice The `int192` field codec, shared by every `int192` field of every table.
library Int192FieldLib {
  function load(Int192Field memory self) internal view returns (int192) {
    return int192(uint192(bytes24(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int192Field memory self, int192 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int192 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int192) {
    return int192(uint192(Bytes.getBytes24(staticData, offset)));
  }
}
