// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `int120` field of a record.
struct Int120Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int120FieldLib for Int120Field global;

/// @notice The `int120` field codec, shared by every `int120` field of every table.
library Int120FieldLib {
  function load(Int120Field memory self) internal view returns (int120) {
    return int120(uint120(bytes15(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int120Field memory self, int120 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int120 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int120) {
    return int120(uint120(Bytes.getBytes15(staticData, offset)));
  }
}
