// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `int136` field of a record.
struct Int136Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int136FieldLib for Int136Field global;

/// @notice The `int136` field codec, shared by every `int136` field of every table.
library Int136FieldLib {
  function load(Int136Field memory self) internal view returns (int136) {
    return int136(uint136(bytes17(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int136Field memory self, int136 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int136 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int136) {
    return int136(uint136(Bytes.getBytes17(staticData, offset)));
  }
}
