// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `int144` field of a record.
struct Int144Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int144FieldLib for Int144Field global;

/// @notice The `int144` field codec, shared by every `int144` field of every table.
library Int144FieldLib {
  function load(Int144Field memory self) internal view returns (int144) {
    return int144(uint144(bytes18(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int144Field memory self, int144 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int144 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int144) {
    return int144(uint144(Bytes.getBytes18(staticData, offset)));
  }
}
