// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `int184` field of a record.
struct Int184Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int184FieldLib for Int184Field global;

/// @notice The `int184` field codec, shared by every `int184` field of every table.
library Int184FieldLib {
  function load(Int184Field memory self) internal view returns (int184) {
    return int184(uint184(bytes23(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int184Field memory self, int184 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int184 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int184) {
    return int184(uint184(Bytes.getBytes23(staticData, offset)));
  }
}
