// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `int128` field of a record.
struct Int128Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int128FieldLib for Int128Field global;

/// @notice The `int128` field codec, shared by every `int128` field of every table.
library Int128FieldLib {
  function load(Int128Field memory self) internal view returns (int128) {
    return int128(uint128(bytes16(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int128Field memory self, int128 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int128 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int128) {
    return int128(uint128(Bytes.getBytes16(staticData, offset)));
  }
}
