// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `int16` field of a record.
struct Int16Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int16FieldLib for Int16Field global;

/// @notice The `int16` field codec, shared by every `int16` field of every table.
library Int16FieldLib {
  function load(Int16Field memory self) internal view returns (int16) {
    return int16(uint16(bytes2(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int16Field memory self, int16 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int16 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int16) {
    return int16(uint16(Bytes.getBytes2(staticData, offset)));
  }
}
