// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `int240` field of a record.
struct Int240Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int240FieldLib for Int240Field global;

/// @notice The `int240` field codec, shared by every `int240` field of every table.
library Int240FieldLib {
  function load(Int240Field memory self) internal view returns (int240) {
    return int240(uint240(bytes30(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int240Field memory self, int240 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int240 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int240) {
    return int240(uint240(Bytes.getBytes30(staticData, offset)));
  }
}
