// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `int24` field of a record.
struct Int24Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int24FieldLib for Int24Field global;

/// @notice The `int24` field codec, shared by every `int24` field of every table.
library Int24FieldLib {
  function load(Int24Field memory self) internal view returns (int24) {
    return int24(uint24(bytes3(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int24Field memory self, int24 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int24 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int24) {
    return int24(uint24(Bytes.getBytes3(staticData, offset)));
  }
}
