// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `int200` field of a record.
struct Int200Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int200FieldLib for Int200Field global;

/// @notice The `int200` field codec, shared by every `int200` field of every table.
library Int200FieldLib {
  function load(Int200Field memory self) internal view returns (int200) {
    return int200(uint200(bytes25(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int200Field memory self, int200 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int200 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int200) {
    return int200(uint200(Bytes.getBytes25(staticData, offset)));
  }
}
