// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `int256` field of a record.
struct Int256Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int256FieldLib for Int256Field global;

/// @notice The `int256` field codec, shared by every `int256` field of every table.
library Int256FieldLib {
  function load(Int256Field memory self) internal view returns (int256) {
    return int256(uint256(bytes32(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int256Field memory self, int256 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int256 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int256) {
    return int256(uint256(Bytes.getBytes32(staticData, offset)));
  }
}
