// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `int48` field of a record.
struct Int48Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int48FieldLib for Int48Field global;

/// @notice The `int48` field codec, shared by every `int48` field of every table.
library Int48FieldLib {
  function load(Int48Field memory self) internal view returns (int48) {
    return int48(uint48(bytes6(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int48Field memory self, int48 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int48 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int48) {
    return int48(uint48(Bytes.getBytes6(staticData, offset)));
  }
}
