// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `int40` field of a record.
struct Int40Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int40FieldLib for Int40Field global;

/// @notice The `int40` field codec, shared by every `int40` field of every table.
library Int40FieldLib {
  function load(Int40Field memory self) internal view returns (int40) {
    return int40(uint40(bytes5(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int40Field memory self, int40 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int40 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int40) {
    return int40(uint40(Bytes.getBytes5(staticData, offset)));
  }
}
