// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `int56` field of a record.
struct Int56Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int56FieldLib for Int56Field global;

/// @notice The `int56` field codec, shared by every `int56` field of every table.
library Int56FieldLib {
  function load(Int56Field memory self) internal view returns (int56) {
    return int56(uint56(bytes7(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int56Field memory self, int56 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int56 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int56) {
    return int56(uint56(Bytes.getBytes7(staticData, offset)));
  }
}
