// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `int88` field of a record.
struct Int88Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int88FieldLib for Int88Field global;

/// @notice The `int88` field codec, shared by every `int88` field of every table.
library Int88FieldLib {
  function load(Int88Field memory self) internal view returns (int88) {
    return int88(uint88(bytes11(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int88Field memory self, int88 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int88 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int88) {
    return int88(uint88(Bytes.getBytes11(staticData, offset)));
  }
}
