// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `uint64` field of a record.
struct Uint64Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint64FieldLib for Uint64Field global;

/// @notice The `uint64` field codec, shared by every `uint64` field of every table.
library Uint64FieldLib {
  function load(Uint64Field memory self) internal view returns (uint64) {
    return uint64(bytes8(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint64Field memory self, uint64 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint64 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint64) {
    return uint64(Bytes.getBytes8(staticData, offset));
  }
}
