// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `uint136` field of a record.
struct Uint136Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint136FieldLib for Uint136Field global;

/// @notice The `uint136` field codec, shared by every `uint136` field of every table.
library Uint136FieldLib {
  function load(Uint136Field memory self) internal view returns (uint136) {
    return uint136(bytes17(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint136Field memory self, uint136 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint136 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint136) {
    return uint136(Bytes.getBytes17(staticData, offset));
  }
}
