// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `uint32` field of a record.
struct Uint32Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint32FieldLib for Uint32Field global;

/// @notice The `uint32` field codec, shared by every `uint32` field of every table.
library Uint32FieldLib {
  function load(Uint32Field memory self) internal view returns (uint32) {
    return uint32(bytes4(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint32Field memory self, uint32 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint32 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint32) {
    return uint32(Bytes.getBytes4(staticData, offset));
  }
}
