// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `uint248` field of a record.
struct Uint248Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint248FieldLib for Uint248Field global;

/// @notice The `uint248` field codec, shared by every `uint248` field of every table.
library Uint248FieldLib {
  function load(Uint248Field memory self) internal view returns (uint248) {
    return uint248(bytes31(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint248Field memory self, uint248 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint248 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint248) {
    return uint248(Bytes.getBytes31(staticData, offset));
  }
}
