// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `uint224` field of a record.
struct Uint224Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint224FieldLib for Uint224Field global;

/// @notice The `uint224` field codec, shared by every `uint224` field of every table.
library Uint224FieldLib {
  function load(Uint224Field memory self) internal view returns (uint224) {
    return uint224(bytes28(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint224Field memory self, uint224 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint224 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint224) {
    return uint224(Bytes.getBytes28(staticData, offset));
  }
}
