// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `uint144` field of a record.
struct Uint144Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint144FieldLib for Uint144Field global;

/// @notice The `uint144` field codec, shared by every `uint144` field of every table.
library Uint144FieldLib {
  function load(Uint144Field memory self) internal view returns (uint144) {
    return uint144(bytes18(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint144Field memory self, uint144 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint144 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint144) {
    return uint144(Bytes.getBytes18(staticData, offset));
  }
}
