// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `uint88` field of a record.
struct Uint88Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint88FieldLib for Uint88Field global;

/// @notice The `uint88` field codec, shared by every `uint88` field of every table.
library Uint88FieldLib {
  function load(Uint88Field memory self) internal view returns (uint88) {
    return uint88(bytes11(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint88Field memory self, uint88 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint88 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint88) {
    return uint88(Bytes.getBytes11(staticData, offset));
  }
}
