// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `uint256` field of a record.
struct Uint256Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint256FieldLib for Uint256Field global;

/// @notice The `uint256` field codec, shared by every `uint256` field of every table.
library Uint256FieldLib {
  function load(Uint256Field memory self) internal view returns (uint256) {
    return uint256(bytes32(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint256Field memory self, uint256 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint256 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint256) {
    return uint256(Bytes.getBytes32(staticData, offset));
  }
}
