// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `uint208` field of a record.
struct Uint208Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint208FieldLib for Uint208Field global;

/// @notice The `uint208` field codec, shared by every `uint208` field of every table.
library Uint208FieldLib {
  function load(Uint208Field memory self) internal view returns (uint208) {
    return uint208(bytes26(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint208Field memory self, uint208 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint208 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint208) {
    return uint208(Bytes.getBytes26(staticData, offset));
  }
}
