// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `uint184` field of a record.
struct Uint184Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint184FieldLib for Uint184Field global;

/// @notice The `uint184` field codec, shared by every `uint184` field of every table.
library Uint184FieldLib {
  function load(Uint184Field memory self) internal view returns (uint184) {
    return uint184(bytes23(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint184Field memory self, uint184 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint184 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint184) {
    return uint184(Bytes.getBytes23(staticData, offset));
  }
}
