// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `uint24` field of a record.
struct Uint24Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint24FieldLib for Uint24Field global;

/// @notice The `uint24` field codec, shared by every `uint24` field of every table.
library Uint24FieldLib {
  function load(Uint24Field memory self) internal view returns (uint24) {
    return uint24(bytes3(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint24Field memory self, uint24 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint24 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint24) {
    return uint24(Bytes.getBytes3(staticData, offset));
  }
}
