// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `uint176` field of a record.
struct Uint176Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint176FieldLib for Uint176Field global;

/// @notice The `uint176` field codec, shared by every `uint176` field of every table.
library Uint176FieldLib {
  function load(Uint176Field memory self) internal view returns (uint176) {
    return uint176(bytes22(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint176Field memory self, uint176 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint176 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint176) {
    return uint176(Bytes.getBytes22(staticData, offset));
  }
}
