// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `uint96` field of a record.
struct Uint96Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint96FieldLib for Uint96Field global;

/// @notice The `uint96` field codec, shared by every `uint96` field of every table.
library Uint96FieldLib {
  function load(Uint96Field memory self) internal view returns (uint96) {
    return uint96(bytes12(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint96Field memory self, uint96 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint96 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint96) {
    return uint96(Bytes.getBytes12(staticData, offset));
  }
}
