// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `uint104` field of a record.
struct Uint104Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint104FieldLib for Uint104Field global;

/// @notice The `uint104` field codec, shared by every `uint104` field of every table.
library Uint104FieldLib {
  function load(Uint104Field memory self) internal view returns (uint104) {
    return uint104(bytes13(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint104Field memory self, uint104 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint104 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint104) {
    return uint104(Bytes.getBytes13(staticData, offset));
  }
}
