// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { EncodedLengths } from "../../EncodedLengths.sol";
import { SliceLib } from "../../Slice.sol";
import { EncodeArray } from "../../tightcoder/EncodeArray.sol";
import { DynamicRange } from "./_dynamic.sol";

/// @notice A handle to one `uint64[]` field of a record.
struct Uint64ArrayField {
  Record record;
  uint8 dynamicIndex;
}

using Uint64ArrayFieldLib for Uint64ArrayField global;

/// @notice The `uint64[]` field codec, shared by every `uint64[]` field of every table.
library Uint64ArrayFieldLib {
  uint256 constant _ELEMENT_SIZE = 8;

  function load(Uint64ArrayField memory self) internal view returns (uint64[] memory) {
    bytes memory blob = StoreAccess.getDynamicField(self.record, self.dynamicIndex);
    return SliceLib.getSubslice(blob, 0, blob.length).decodeArray_uint64();
  }

  function save(Uint64ArrayField memory self, uint64[] memory value) internal {
    StoreAccess.setDynamicField(self.record, self.dynamicIndex, EncodeArray.encode(value));
  }

  /// @notice Number of elements.
  function length(Uint64ArrayField memory self) internal view returns (uint256) {
    return StoreAccess.getDynamicFieldLength(self.record, self.dynamicIndex) / _ELEMENT_SIZE;
  }

  /// @notice Load one element by index.
  function load(Uint64ArrayField memory self, uint256 index) internal view returns (uint64) {
    bytes memory blob = StoreAccess.getDynamicFieldSlice(
      self.record,
      self.dynamicIndex,
      index * _ELEMENT_SIZE,
      (index + 1) * _ELEMENT_SIZE
    );
    return uint64(bytes8(blob));
  }

  /// @notice Overwrite one element by index.
  function save(Uint64ArrayField memory self, uint256 index, uint64 element) internal {
    StoreAccess.spliceDynamicData(
      self.record,
      self.dynamicIndex,
      uint40(index * _ELEMENT_SIZE),
      uint40(_ELEMENT_SIZE),
      abi.encodePacked(element)
    );
  }

  function push(Uint64ArrayField memory self, uint64 element) internal {
    StoreAccess.pushToDynamicField(self.record, self.dynamicIndex, abi.encodePacked(element));
  }

  function pop(Uint64ArrayField memory self) internal {
    StoreAccess.popFromDynamicField(self.record, self.dynamicIndex, _ELEMENT_SIZE);
  }

  function encode(uint64[] memory value) internal pure returns (bytes memory) {
    return EncodeArray.encode(value);
  }

  function byteLength(uint64[] memory value) internal pure returns (uint256) {
    return value.length * _ELEMENT_SIZE;
  }

  function decode(
    bytes memory dynamicData,
    EncodedLengths encodedLengths,
    uint8 dynamicIndex
  ) internal pure returns (uint64[] memory) {
    (uint256 start, uint256 end) = DynamicRange.range(encodedLengths, dynamicIndex);
    return SliceLib.getSubslice(dynamicData, start, end).decodeArray_uint64();
  }
}
