// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `uint160` field of a record.
struct Uint160Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint160FieldLib for Uint160Field global;

/// @notice The `uint160` field codec, shared by every `uint160` field of every table.
library Uint160FieldLib {
  function load(Uint160Field memory self) internal view returns (uint160) {
    return uint160(bytes20(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint160Field memory self, uint160 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint160 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint160) {
    return uint160(Bytes.getBytes20(staticData, offset));
  }
}
