// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Bytes } from "../../Bytes.sol";

/// @notice A handle to one `uint112` field of a record.
struct Uint112Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint112FieldLib for Uint112Field global;

/// @notice The `uint112` field codec, shared by every `uint112` field of every table.
library Uint112FieldLib {
  function load(Uint112Field memory self) internal view returns (uint112) {
    return uint112(bytes14(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint112Field memory self, uint112 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint112 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint112) {
    return uint112(Bytes.getBytes14(staticData, offset));
  }
}
