// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, RecordMethods } from "../../../src/v3/Record.sol";
import { StoreSwitch } from "../../../src/StoreSwitch.sol";
import { ResourceId } from "../../../src/ResourceId.sol";
import { FieldLayout } from "../../../src/FieldLayout.sol";
import { Schema } from "../../../src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "../../../src/EncodedLengths.sol";
import { Bytes24ArrayField, Bytes24ArrayFieldLib } from "../../../src/v3/fields/Bytes24ArrayField.sol";

struct CallbacksData {
  bytes24[] value;
}

/// @notice The Callbacks record at the given key, bound to the canonical table id.
function Callbacks(bytes32 key) pure returns (CallbacksRecord memory) {
  return CallbacksRecord(Record(CallbacksRecordMethods._tableId, CallbacksRecordMethods._encodeKey(key), address(0)));
}

struct CallbacksRecord {
  Record record;
}

using CallbacksRecordMethods for CallbacksRecord global;

library CallbacksRecordMethods {
  ResourceId constant _tableId = ResourceId.wrap(0x7462000000000000000000000000000043616c6c6261636b7300000000000000);
  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0000000100000000000000000000000000000000000000000000000000000000);
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  Schema constant _valueSchema = Schema.wrap(0x00000001b9000000000000000000000000000000000000000000000000000000);

  /// @notice Operate on a non-canonical table id (e.g. a module's namespaced instance).
  function at(CallbacksRecord memory self, ResourceId tableId) internal pure returns (CallbacksRecord memory) {
    self.record.tableId = tableId;
    return self;
  }

  /// @notice Declare this contract's own storage as the store (skips StoreSwitch inference).
  function own(CallbacksRecord memory self) internal view returns (CallbacksRecord memory) {
    self.record.store = address(this);
    return self;
  }

  /// @notice Declare an explicit store to read/write.
  function own(CallbacksRecord memory self, address store) internal pure returns (CallbacksRecord memory) {
    self.record.store = store;
    return self;
  }

  /// @notice Read the whole record and decode it into a memory struct.
  function load(CallbacksRecord memory self) internal view returns (CallbacksData memory) {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = RecordMethods.load(
      self.record
    );
    return _decode(staticData, encodedLengths, dynamicData);
  }

  /// @notice Encode and write the whole record.
  function save(CallbacksRecord memory self, CallbacksData memory data) internal {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = _encode(data);
    RecordMethods.save(self.record, staticData, encodedLengths, dynamicData);
  }

  /// @notice Delete the whole record.
  function destroy(CallbacksRecord memory self) internal {
    RecordMethods.destroy(self.record);
  }

  /// @notice Handle for the `value` field.
  function value(CallbacksRecord memory self) internal pure returns (Bytes24ArrayField memory) {
    return Bytes24ArrayField(self.record, 0);
  }

  /// @notice Encode the key tuple — a primitive for composing direct store calls.
  function _encodeKey(bytes32 key) internal pure returns (bytes32[] memory keyTuple) {
    keyTuple = new bytes32[](1);
    keyTuple[0] = key;
  }

  /// @notice Recover the typed key from a raw keyTuple (e.g. inside a store hook).
  function _decodeKey(bytes32[] memory keyTuple) internal pure returns (bytes32 key) {
    key = keyTuple[0];
  }

  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "key";
  }

  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](1);
    fieldNames[0] = "value";
  }

  /// @notice Register this table. Use the low-level `StoreCore.registerTable` with the
  ///         `_*` constants + name getters to register against a specific store.
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /// @notice Encode `CallbacksData` into the store's (static, lengths, dynamic) triple.
  function _encode(CallbacksData memory data) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory staticData = abi.encodePacked();

    EncodedLengths encodedLengths = EncodedLengthsLib.pack(Bytes24ArrayFieldLib.byteLength(data.value));
    bytes memory dynamicData = abi.encodePacked(Bytes24ArrayFieldLib.encode(data.value));
    return (staticData, encodedLengths, dynamicData);
  }

  /// @notice Decode the store's (static, lengths, dynamic) triple into `CallbacksData`.
  function _decode(
    bytes memory staticData,
    EncodedLengths encodedLengths,
    bytes memory dynamicData
  ) internal pure returns (CallbacksData memory data) {
    data.value = Bytes24ArrayFieldLib.decode(dynamicData, encodedLengths, 0);
  }
}
