// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Uint8Field, Uint8FieldLib } from "../../../src/fields/Uint8Field.sol";
import { ExampleEnum } from "./ExampleEnum.sol";

/// @notice A handle to one `ExampleEnum` field (a enum over `uint8`).
struct ExampleEnumField {
  Uint8Field inner;
}

using ExampleEnumFieldLib for ExampleEnumField global;

/// @notice The `ExampleEnum` field codec: delegates to `Uint8FieldLib`, converting at the boundary.
library ExampleEnumFieldLib {
  function load(ExampleEnumField memory self) internal view returns (ExampleEnum) {
    return ExampleEnum(self.inner.load());
  }

  function save(ExampleEnumField memory self, ExampleEnum value) internal {
    self.inner.save(uint8(value));
  }

  function encode(ExampleEnum value) internal pure returns (bytes memory) {
    return Uint8FieldLib.encode(uint8(value));
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (ExampleEnum) {
    return ExampleEnum(Uint8FieldLib.decode(staticData, offset));
  }
}
