// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, RecordMethods } from "../../../src/Record.sol";
import { StoreSwitch } from "../../../src/StoreSwitch.sol";
import { ResourceId } from "../../../src/ResourceId.sol";
import { FieldLayout } from "../../../src/FieldLayout.sol";
import { Schema } from "../../../src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "../../../src/EncodedLengths.sol";
import { Bytes } from "../../../src/Bytes.sol";

import { BoolField, BoolFieldLib } from "../../../src/fields/BoolField.sol";

import { ExampleEnum } from "./ExampleEnum.sol";

struct KeyEncodingData {
  bool value;
}

/// @notice The KeyEncoding record at the given key, bound to the canonical table id.
function KeyEncoding(
  uint256 k1,
  int32 k2,
  bytes16 k3,
  address k4,
  bool k5,
  ExampleEnum k6
) pure returns (KeyEncodingRecord memory) {
  return
    KeyEncodingRecord(
      Record(KeyEncodingRecordMethods._tableId, KeyEncodingRecordMethods._encodeKey(k1, k2, k3, k4, k5, k6), address(0))
    );
}

struct KeyEncodingRecord {
  Record record;
}

using KeyEncodingRecordMethods for KeyEncodingRecord global;

library KeyEncodingRecordMethods {
  ResourceId constant _tableId = ResourceId.wrap(0x746200000000000000000000000000004b6579456e636f64696e670000000000);
  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0001010001000000000000000000000000000000000000000000000000000000);
  Schema constant _keySchema = Schema.wrap(0x004a06001f234f61600000000000000000000000000000000000000000000000);
  Schema constant _valueSchema = Schema.wrap(0x0001010060000000000000000000000000000000000000000000000000000000);

  /// @notice Operate on a non-canonical table id (e.g. a module's namespaced instance).
  function at(KeyEncodingRecord memory self, ResourceId tableId) internal pure returns (KeyEncodingRecord memory) {
    self.record.tableId = tableId;
    return self;
  }

  /// @notice Declare this contract's own storage as the store (skips StoreSwitch inference).
  function own(KeyEncodingRecord memory self) internal view returns (KeyEncodingRecord memory) {
    self.record.store = address(this);
    return self;
  }

  /// @notice Declare an explicit store to read/write.
  function own(KeyEncodingRecord memory self, address store) internal pure returns (KeyEncodingRecord memory) {
    self.record.store = store;
    return self;
  }

  /// @notice Read the whole record and decode it into a memory struct.
  /// @dev Passes the table's constant `_fieldLayout`, skipping the store's layout lookup.
  function load(KeyEncodingRecord memory self) internal view returns (KeyEncodingData memory) {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = RecordMethods.load(
      self.record,
      _fieldLayout
    );
    return _decode(staticData, encodedLengths, dynamicData);
  }

  /// @notice Encode and write the whole record.
  function save(KeyEncodingRecord memory self, KeyEncodingData memory data) internal {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = _encode(data);
    RecordMethods.save(self.record, staticData, encodedLengths, dynamicData, _fieldLayout);
  }

  /// @notice Delete the whole record.
  function destroy(KeyEncodingRecord memory self) internal {
    RecordMethods.destroy(self.record, _fieldLayout);
  }

  /// @notice Handle for the `value` field.
  function value(KeyEncodingRecord memory self) internal pure returns (BoolField memory) {
    return BoolField(self.record, _fieldLayout, 0);
  }

  /// @notice Encode the key tuple — a primitive for composing direct store calls.
  function _encodeKey(
    uint256 k1,
    int32 k2,
    bytes16 k3,
    address k4,
    bool k5,
    ExampleEnum k6
  ) internal pure returns (bytes32[] memory keyTuple) {
    keyTuple = new bytes32[](6);
    keyTuple[0] = bytes32(uint256(k1));
    keyTuple[1] = bytes32(uint256(int256(k2)));
    keyTuple[2] = bytes32(k3);
    keyTuple[3] = bytes32(uint256(uint160(k4)));
    keyTuple[4] = bytes32(uint256(k5 ? 1 : 0));
    keyTuple[5] = bytes32(uint256(uint8(k6)));
  }

  /// @notice Recover the typed key from a raw keyTuple (e.g. inside a store hook).
  function _decodeKey(
    bytes32[] memory keyTuple
  ) internal pure returns (uint256 k1, int32 k2, bytes16 k3, address k4, bool k5, ExampleEnum k6) {
    k1 = uint256(uint256(keyTuple[0]));
    k2 = int32(uint32(uint256(keyTuple[1])));
    k3 = bytes16(keyTuple[2]);
    k4 = address(uint160(uint256(keyTuple[3])));
    k5 = uint256(keyTuple[4]) != 0;
    k6 = ExampleEnum(uint8(uint256(keyTuple[5])));
  }

  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](6);
    keyNames[0] = "k1";
    keyNames[1] = "k2";
    keyNames[2] = "k3";
    keyNames[3] = "k4";
    keyNames[4] = "k5";
    keyNames[5] = "k6";
  }

  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](1);
    fieldNames[0] = "value";
  }

  /// @notice Register this table. Use the low-level `StoreCore.registerTable` with the
  ///         `_*` constants + name getters to register against a specific store.
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /// @notice Encode `KeyEncodingData` into the store's (static, lengths, dynamic) triple.
  function _encode(KeyEncodingData memory data) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory staticData = abi.encodePacked(data.value);
    return (staticData, EncodedLengths.wrap(bytes32(0)), new bytes(0));
  }

  /// @notice Decode the store's (static, lengths, dynamic) triple into `KeyEncodingData`.
  function _decode(
    bytes memory staticData,
    EncodedLengths encodedLengths,
    bytes memory dynamicData
  ) internal pure returns (KeyEncodingData memory data) {
    data.value = uint8(Bytes.getBytes1(staticData, 0)) != 0;
  }
}
