// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, RecordMethods } from "../../../src/v3/Record.sol";
import { StoreSwitch } from "../../../src/StoreSwitch.sol";
import { ResourceId } from "../../../src/ResourceId.sol";
import { FieldLayout } from "../../../src/FieldLayout.sol";
import { Schema } from "../../../src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "../../../src/EncodedLengths.sol";
import { Uint32Field, Uint32FieldLib } from "../../../src/v3/fields/Uint32Field.sol";
import { Uint128Field, Uint128FieldLib } from "../../../src/v3/fields/Uint128Field.sol";
import { Uint32ArrayField, Uint32ArrayFieldLib } from "../../../src/v3/fields/Uint32ArrayField.sol";
import { StringField, StringFieldLib } from "../../../src/v3/fields/StringField.sol";

struct MixedData {
  uint32 u32;
  uint128 u128;
  uint32[] a32;
  string s;
}

/// @notice The Mixed record at the given key, bound to the canonical table id.
function Mixed(bytes32 key) pure returns (MixedRecord memory) {
  return MixedRecord(Record(MixedRecordMethods._tableId, MixedRecordMethods._encodeKey(key), address(0)));
}

struct MixedRecord {
  Record record;
}

using MixedRecordMethods for MixedRecord global;

library MixedRecordMethods {
  ResourceId constant _tableId = ResourceId.wrap(0x746200000000000000000000000000004d697865640000000000000000000000);
  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0014020204100000000000000000000000000000000000000000000000000000);
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  Schema constant _valueSchema = Schema.wrap(0x00140202030f65c5000000000000000000000000000000000000000000000000);

  /// @notice Operate on a non-canonical table id (e.g. a module's namespaced instance).
  function at(MixedRecord memory self, ResourceId tableId) internal pure returns (MixedRecord memory) {
    self.record.tableId = tableId;
    return self;
  }

  /// @notice Declare this contract's own storage as the store (skips StoreSwitch inference).
  function own(MixedRecord memory self) internal view returns (MixedRecord memory) {
    self.record.store = address(this);
    return self;
  }

  /// @notice Declare an explicit store to read/write.
  function own(MixedRecord memory self, address store) internal pure returns (MixedRecord memory) {
    self.record.store = store;
    return self;
  }

  /// @notice Read the whole record and decode it into a memory struct.
  function load(MixedRecord memory self) internal view returns (MixedData memory) {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = RecordMethods.load(
      self.record
    );
    return _decode(staticData, encodedLengths, dynamicData);
  }

  /// @notice Encode and write the whole record.
  function save(MixedRecord memory self, MixedData memory data) internal {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = _encode(data);
    RecordMethods.save(self.record, staticData, encodedLengths, dynamicData);
  }

  /// @notice Delete the whole record.
  function destroy(MixedRecord memory self) internal {
    RecordMethods.destroy(self.record);
  }

  /// @notice Handle for the `u32` field.
  function u32(MixedRecord memory self) internal pure returns (Uint32Field memory) {
    return Uint32Field(self.record, _fieldLayout, 0);
  }

  /// @notice Handle for the `u128` field.
  function u128(MixedRecord memory self) internal pure returns (Uint128Field memory) {
    return Uint128Field(self.record, _fieldLayout, 1);
  }

  /// @notice Handle for the `a32` field.
  function a32(MixedRecord memory self) internal pure returns (Uint32ArrayField memory) {
    return Uint32ArrayField(self.record, 0);
  }

  /// @notice Handle for the `s` field.
  function s(MixedRecord memory self) internal pure returns (StringField memory) {
    return StringField(self.record, 1);
  }

  /// @notice Encode the key tuple — a primitive for composing direct store calls.
  function _encodeKey(bytes32 key) internal pure returns (bytes32[] memory keyTuple) {
    keyTuple = new bytes32[](1);
    keyTuple[0] = key;
  }

  /// @notice Recover the typed key from a raw keyTuple (e.g. inside a store hook).
  function _decodeKey(bytes32[] memory keyTuple) internal pure returns (bytes32 key) {
    key = keyTuple[0];
  }

  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "key";
  }

  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](4);
    fieldNames[0] = "u32";
    fieldNames[1] = "u128";
    fieldNames[2] = "a32";
    fieldNames[3] = "s";
  }

  /// @notice Register this table. Use the low-level `StoreCore.registerTable` with the
  ///         `_*` constants + name getters to register against a specific store.
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /// @notice Encode `MixedData` into the store's (static, lengths, dynamic) triple.
  function _encode(MixedData memory data) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory staticData = abi.encodePacked(Uint32FieldLib.encode(data.u32), Uint128FieldLib.encode(data.u128));

    EncodedLengths encodedLengths = EncodedLengthsLib.pack(
      Uint32ArrayFieldLib.byteLength(data.a32),
      StringFieldLib.byteLength(data.s)
    );
    bytes memory dynamicData = abi.encodePacked(Uint32ArrayFieldLib.encode(data.a32), StringFieldLib.encode(data.s));
    return (staticData, encodedLengths, dynamicData);
  }

  /// @notice Decode the store's (static, lengths, dynamic) triple into `MixedData`.
  function _decode(
    bytes memory staticData,
    EncodedLengths encodedLengths,
    bytes memory dynamicData
  ) internal pure returns (MixedData memory data) {
    data.u32 = Uint32FieldLib.decode(staticData, 0);
    data.u128 = Uint128FieldLib.decode(staticData, 4);
    data.a32 = Uint32ArrayFieldLib.decode(dynamicData, encodedLengths, 0);
    data.s = StringFieldLib.decode(dynamicData, encodedLengths, 1);
  }
}
