// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, RecordMethods } from "../../../src/v3/Record.sol";
import { StoreSwitch } from "../../../src/StoreSwitch.sol";
import { ResourceId } from "../../../src/ResourceId.sol";
import { FieldLayout } from "../../../src/FieldLayout.sol";
import { Schema } from "../../../src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "../../../src/EncodedLengths.sol";
import { Bytes } from "../../../src/Bytes.sol";

import { Uint32Field, Uint32FieldLib } from "../../../src/v3/fields/Uint32Field.sol";

struct Vector2Data {
  uint32 x;
  uint32 y;
}

/// @notice The Vector2 record at the given key, bound to the canonical table id.
function Vector2(bytes32 key) pure returns (Vector2Record memory) {
  return Vector2Record(Record(Vector2RecordMethods._tableId, Vector2RecordMethods._encodeKey(key), address(0)));
}

struct Vector2Record {
  Record record;
}

using Vector2RecordMethods for Vector2Record global;

library Vector2RecordMethods {
  ResourceId constant _tableId = ResourceId.wrap(0x74620000000000000000000000000000566563746f7232000000000000000000);
  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0008020004040000000000000000000000000000000000000000000000000000);
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  Schema constant _valueSchema = Schema.wrap(0x0008020003030000000000000000000000000000000000000000000000000000);

  /// @notice Operate on a non-canonical table id (e.g. a module's namespaced instance).
  function at(Vector2Record memory self, ResourceId tableId) internal pure returns (Vector2Record memory) {
    self.record.tableId = tableId;
    return self;
  }

  /// @notice Declare this contract's own storage as the store (skips StoreSwitch inference).
  function own(Vector2Record memory self) internal view returns (Vector2Record memory) {
    self.record.store = address(this);
    return self;
  }

  /// @notice Declare an explicit store to read/write.
  function own(Vector2Record memory self, address store) internal pure returns (Vector2Record memory) {
    self.record.store = store;
    return self;
  }

  /// @notice Read the whole record and decode it into a memory struct.
  /// @dev Passes the table's constant `_fieldLayout`, skipping the store's layout lookup.
  function load(Vector2Record memory self) internal view returns (Vector2Data memory) {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = RecordMethods.load(
      self.record,
      _fieldLayout
    );
    return _decode(staticData, encodedLengths, dynamicData);
  }

  /// @notice Encode and write the whole record.
  function save(Vector2Record memory self, Vector2Data memory data) internal {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = _encode(data);
    RecordMethods.save(self.record, staticData, encodedLengths, dynamicData, _fieldLayout);
  }

  /// @notice Delete the whole record.
  function destroy(Vector2Record memory self) internal {
    RecordMethods.destroy(self.record, _fieldLayout);
  }

  /// @notice Handle for the `x` field.
  function x(Vector2Record memory self) internal pure returns (Uint32Field memory) {
    return Uint32Field(self.record, _fieldLayout, 0);
  }

  /// @notice Handle for the `y` field.
  function y(Vector2Record memory self) internal pure returns (Uint32Field memory) {
    return Uint32Field(self.record, _fieldLayout, 1);
  }

  /// @notice Encode the key tuple — a primitive for composing direct store calls.
  function _encodeKey(bytes32 key) internal pure returns (bytes32[] memory keyTuple) {
    keyTuple = new bytes32[](1);
    keyTuple[0] = key;
  }

  /// @notice Recover the typed key from a raw keyTuple (e.g. inside a store hook).
  function _decodeKey(bytes32[] memory keyTuple) internal pure returns (bytes32 key) {
    key = keyTuple[0];
  }

  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "key";
  }

  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "x";
    fieldNames[1] = "y";
  }

  /// @notice Register this table. Use the low-level `StoreCore.registerTable` with the
  ///         `_*` constants + name getters to register against a specific store.
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /// @notice Encode `Vector2Data` into the store's (static, lengths, dynamic) triple.
  function _encode(Vector2Data memory data) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory staticData = abi.encodePacked(data.x, data.y);
    return (staticData, EncodedLengths.wrap(bytes32(0)), new bytes(0));
  }

  /// @notice Decode the store's (static, lengths, dynamic) triple into `Vector2Data`.
  function _decode(
    bytes memory staticData,
    EncodedLengths encodedLengths,
    bytes memory dynamicData
  ) internal pure returns (Vector2Data memory data) {
    data.x = uint32(Bytes.getBytes4(staticData, 0));
    data.y = uint32(Bytes.getBytes4(staticData, 4));
  }
}
