// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, RecordMethods } from "../../v3/Record.sol";
import { StoreSwitch } from "../../StoreSwitch.sol";
import { ResourceId } from "../../ResourceId.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Schema } from "../../Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "../../EncodedLengths.sol";
import { Bytes21ArrayField, Bytes21ArrayFieldLib } from "../../v3/fields/Bytes21ArrayField.sol";

import { ResourceId } from "../../ResourceId.sol";

struct StoreHooksData {
  bytes21[] hooks;
}

/// @notice The StoreHooks record at the given key, bound to the canonical table id.
function StoreHooks(ResourceId tableId) pure returns (StoreHooksRecord memory) {
  return
    StoreHooksRecord(Record(StoreHooksRecordMethods._tableId, StoreHooksRecordMethods._encodeKey(tableId), address(0)));
}

struct StoreHooksRecord {
  Record record;
}

using StoreHooksRecordMethods for StoreHooksRecord global;

library StoreHooksRecordMethods {
  ResourceId constant _tableId = ResourceId.wrap(0x746273746f726500000000000000000053746f7265486f6f6b73000000000000);
  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0000000100000000000000000000000000000000000000000000000000000000);
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  Schema constant _valueSchema = Schema.wrap(0x00000001b6000000000000000000000000000000000000000000000000000000);

  /// @notice Operate on a non-canonical table id (e.g. a module's namespaced instance).
  function at(StoreHooksRecord memory self, ResourceId tableId) internal pure returns (StoreHooksRecord memory) {
    self.record.tableId = tableId;
    return self;
  }

  /// @notice Declare this contract's own storage as the store (skips StoreSwitch inference).
  function own(StoreHooksRecord memory self) internal view returns (StoreHooksRecord memory) {
    self.record.store = address(this);
    return self;
  }

  /// @notice Declare an explicit store to read/write.
  function own(StoreHooksRecord memory self, address store) internal pure returns (StoreHooksRecord memory) {
    self.record.store = store;
    return self;
  }

  /// @notice Read the whole record and decode it into a memory struct.
  function load(StoreHooksRecord memory self) internal view returns (StoreHooksData memory) {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = RecordMethods.load(
      self.record
    );
    return _decode(staticData, encodedLengths, dynamicData);
  }

  /// @notice Encode and write the whole record.
  function save(StoreHooksRecord memory self, StoreHooksData memory data) internal {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = _encode(data);
    RecordMethods.save(self.record, staticData, encodedLengths, dynamicData);
  }

  /// @notice Delete the whole record.
  function destroy(StoreHooksRecord memory self) internal {
    RecordMethods.destroy(self.record);
  }

  /// @notice Handle for the `hooks` field.
  function hooks(StoreHooksRecord memory self) internal pure returns (Bytes21ArrayField memory) {
    return Bytes21ArrayField(self.record, 0);
  }

  /// @notice Encode the key tuple — a primitive for composing direct store calls.
  function _encodeKey(ResourceId tableId) internal pure returns (bytes32[] memory keyTuple) {
    keyTuple = new bytes32[](1);
    keyTuple[0] = ResourceId.unwrap(tableId);
  }

  /// @notice Recover the typed key from a raw keyTuple (e.g. inside a store hook).
  function _decodeKey(bytes32[] memory keyTuple) internal pure returns (ResourceId tableId) {
    tableId = ResourceId.wrap(keyTuple[0]);
  }

  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "tableId";
  }

  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](1);
    fieldNames[0] = "hooks";
  }

  /// @notice Register this table. Use the low-level `StoreCore.registerTable` with the
  ///         `_*` constants + name getters to register against a specific store.
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /// @notice Encode `StoreHooksData` into the store's (static, lengths, dynamic) triple.
  function _encode(StoreHooksData memory data) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory staticData = abi.encodePacked();

    EncodedLengths encodedLengths = EncodedLengthsLib.pack(Bytes21ArrayFieldLib.byteLength(data.hooks));
    bytes memory dynamicData = abi.encodePacked(Bytes21ArrayFieldLib.encode(data.hooks));
    return (staticData, encodedLengths, dynamicData);
  }

  /// @notice Decode the store's (static, lengths, dynamic) triple into `StoreHooksData`.
  function _decode(
    bytes memory staticData,
    EncodedLengths encodedLengths,
    bytes memory dynamicData
  ) internal pure returns (StoreHooksData memory data) {
    data.hooks = Bytes21ArrayFieldLib.decode(dynamicData, encodedLengths, 0);
  }
}
