// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, RecordMethods } from "../../v3/Record.sol";
import { StoreSwitch } from "../../StoreSwitch.sol";
import { ResourceId } from "../../ResourceId.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Schema } from "../../Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "../../EncodedLengths.sol";
import { BytesField, BytesFieldLib } from "../../v3/fields/BytesField.sol";
import { Bytes32Field } from "../../v3/fields/Bytes32Field.sol";
import { FieldLayoutField, FieldLayoutFieldLib } from "./FieldLayoutField.sol";
import { SchemaField, SchemaFieldLib } from "./SchemaField.sol";
import { FieldLayout } from "../../FieldLayout.sol";
import { Schema } from "../../Schema.sol";
import { ResourceId } from "../../ResourceId.sol";

struct TablesData {
  FieldLayout fieldLayout;
  Schema keySchema;
  Schema valueSchema;
  bytes abiEncodedKeyNames;
  bytes abiEncodedFieldNames;
}

/// @notice The Tables record at the given key, bound to the canonical table id.
function Tables(ResourceId tableId) pure returns (TablesRecord memory) {
  return TablesRecord(Record(TablesRecordMethods._tableId, TablesRecordMethods._encodeKey(tableId), address(0)));
}

struct TablesRecord {
  Record record;
}

using TablesRecordMethods for TablesRecord global;

library TablesRecordMethods {
  ResourceId constant _tableId = ResourceId.wrap(0x746273746f72650000000000000000005461626c657300000000000000000000);
  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0060030220202000000000000000000000000000000000000000000000000000);
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  Schema constant _valueSchema = Schema.wrap(0x006003025f5f5fc4c40000000000000000000000000000000000000000000000);

  /// @notice Operate on a non-canonical table id (e.g. a module's namespaced instance).
  function at(TablesRecord memory self, ResourceId tableId) internal pure returns (TablesRecord memory) {
    self.record.tableId = tableId;
    return self;
  }

  /// @notice Declare this contract's own storage as the store (skips StoreSwitch inference).
  function own(TablesRecord memory self) internal view returns (TablesRecord memory) {
    self.record.store = address(this);
    return self;
  }

  /// @notice Declare an explicit store to read/write.
  function own(TablesRecord memory self, address store) internal pure returns (TablesRecord memory) {
    self.record.store = store;
    return self;
  }

  /// @notice Read the whole record and decode it into a memory struct.
  function load(TablesRecord memory self) internal view returns (TablesData memory) {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = RecordMethods.load(
      self.record
    );
    return _decode(staticData, encodedLengths, dynamicData);
  }

  /// @notice Encode and write the whole record.
  function save(TablesRecord memory self, TablesData memory data) internal {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = _encode(data);
    RecordMethods.save(self.record, staticData, encodedLengths, dynamicData);
  }

  /// @notice Delete the whole record.
  function destroy(TablesRecord memory self) internal {
    RecordMethods.destroy(self.record);
  }

  /// @notice Handle for the `fieldLayout` field.
  function fieldLayout(TablesRecord memory self) internal pure returns (FieldLayoutField memory) {
    return FieldLayoutField(Bytes32Field(self.record, _fieldLayout, 0));
  }

  /// @notice Handle for the `keySchema` field.
  function keySchema(TablesRecord memory self) internal pure returns (SchemaField memory) {
    return SchemaField(Bytes32Field(self.record, _fieldLayout, 1));
  }

  /// @notice Handle for the `valueSchema` field.
  function valueSchema(TablesRecord memory self) internal pure returns (SchemaField memory) {
    return SchemaField(Bytes32Field(self.record, _fieldLayout, 2));
  }

  /// @notice Handle for the `abiEncodedKeyNames` field.
  function abiEncodedKeyNames(TablesRecord memory self) internal pure returns (BytesField memory) {
    return BytesField(self.record, 0);
  }

  /// @notice Handle for the `abiEncodedFieldNames` field.
  function abiEncodedFieldNames(TablesRecord memory self) internal pure returns (BytesField memory) {
    return BytesField(self.record, 1);
  }

  /// @notice Encode the key tuple — a primitive for composing direct store calls.
  function _encodeKey(ResourceId tableId) internal pure returns (bytes32[] memory keyTuple) {
    keyTuple = new bytes32[](1);
    keyTuple[0] = ResourceId.unwrap(tableId);
  }

  /// @notice Recover the typed key from a raw keyTuple (e.g. inside a store hook).
  function _decodeKey(bytes32[] memory keyTuple) internal pure returns (ResourceId tableId) {
    tableId = ResourceId.wrap(keyTuple[0]);
  }

  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "tableId";
  }

  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](5);
    fieldNames[0] = "fieldLayout";
    fieldNames[1] = "keySchema";
    fieldNames[2] = "valueSchema";
    fieldNames[3] = "abiEncodedKeyNames";
    fieldNames[4] = "abiEncodedFieldNames";
  }

  /// @notice Register this table. Use the low-level `StoreCore.registerTable` with the
  ///         `_*` constants + name getters to register against a specific store.
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /// @notice Encode `TablesData` into the store's (static, lengths, dynamic) triple.
  function _encode(TablesData memory data) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory staticData = abi.encodePacked(
      FieldLayoutFieldLib.encode(data.fieldLayout),
      SchemaFieldLib.encode(data.keySchema),
      SchemaFieldLib.encode(data.valueSchema)
    );

    EncodedLengths encodedLengths = EncodedLengthsLib.pack(
      BytesFieldLib.byteLength(data.abiEncodedKeyNames),
      BytesFieldLib.byteLength(data.abiEncodedFieldNames)
    );
    bytes memory dynamicData = abi.encodePacked(
      BytesFieldLib.encode(data.abiEncodedKeyNames),
      BytesFieldLib.encode(data.abiEncodedFieldNames)
    );
    return (staticData, encodedLengths, dynamicData);
  }

  /// @notice Decode the store's (static, lengths, dynamic) triple into `TablesData`.
  function _decode(
    bytes memory staticData,
    EncodedLengths encodedLengths,
    bytes memory dynamicData
  ) internal pure returns (TablesData memory data) {
    data.fieldLayout = FieldLayoutFieldLib.decode(staticData, 0);
    data.keySchema = SchemaFieldLib.decode(staticData, 32);
    data.valueSchema = SchemaFieldLib.decode(staticData, 64);
    data.abiEncodedKeyNames = BytesFieldLib.decode(dynamicData, encodedLengths, 0);
    data.abiEncodedFieldNames = BytesFieldLib.decode(dynamicData, encodedLengths, 1);
  }
}
