// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Bytes32Field, Bytes32FieldLib } from "../../../src/v3/fields/Bytes32Field.sol";
import { FieldLayout } from "../../../src/FieldLayout.sol";

/// @notice A handle to one `FieldLayout` field (a UDVT over `bytes32`).
struct FieldLayoutField {
  Bytes32Field inner;
}

using FieldLayoutFieldLib for FieldLayoutField global;

/// @notice The `FieldLayout` field codec: delegates to `Bytes32FieldLib`, converting at the boundary.
library FieldLayoutFieldLib {
  function load(FieldLayoutField memory self) internal view returns (FieldLayout) {
    return FieldLayout.wrap(self.inner.load());
  }

  function save(FieldLayoutField memory self, FieldLayout value) internal {
    self.inner.save(FieldLayout.unwrap(value));
  }

  function encode(FieldLayout value) internal pure returns (bytes memory) {
    return Bytes32FieldLib.encode(FieldLayout.unwrap(value));
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (FieldLayout) {
    return FieldLayout.wrap(Bytes32FieldLib.decode(staticData, offset));
  }
}
