// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, RecordMethods } from "../../../src/Record.sol";
import { StoreSwitch } from "../../../src/StoreSwitch.sol";
import { ResourceId } from "../../../src/ResourceId.sol";
import { FieldLayout } from "../../../src/FieldLayout.sol";
import { Schema } from "../../../src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "../../../src/EncodedLengths.sol";
import { Bytes } from "../../../src/Bytes.sol";

import { Uint256Field, Uint256FieldLib } from "../../../src/fields/Uint256Field.sol";

struct KeyedData {
  uint256 value;
}

/// @notice The Keyed record at the given key, bound to the canonical table id.
function Keyed(uint256 a, int32 b, address c, bool d, bytes16 e) pure returns (KeyedRecord memory) {
  return KeyedRecord(Record(KeyedRecordMethods._tableId, KeyedRecordMethods._encodeKey(a, b, c, d, e), address(0)));
}

struct KeyedRecord {
  Record record;
}

using KeyedRecordMethods for KeyedRecord global;

library KeyedRecordMethods {
  ResourceId constant _tableId = ResourceId.wrap(0x746200000000000000000000000000004b657965640000000000000000000000);
  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0020010020000000000000000000000000000000000000000000000000000000);
  Schema constant _keySchema = Schema.wrap(0x004905001f2361604f0000000000000000000000000000000000000000000000);
  Schema constant _valueSchema = Schema.wrap(0x002001001f000000000000000000000000000000000000000000000000000000);

  /// @notice Operate on a non-canonical table id (e.g. a module's namespaced instance).
  function at(KeyedRecord memory self, ResourceId tableId) internal pure returns (KeyedRecord memory) {
    self.record.tableId = tableId;
    return self;
  }

  /// @notice Declare this contract's own storage as the store (skips StoreSwitch inference).
  function own(KeyedRecord memory self) internal view returns (KeyedRecord memory) {
    self.record.store = address(this);
    return self;
  }

  /// @notice Declare an explicit store to read/write.
  function own(KeyedRecord memory self, address store) internal pure returns (KeyedRecord memory) {
    self.record.store = store;
    return self;
  }

  /// @notice Read the whole record and decode it into a memory struct.
  /// @dev Passes the table's constant `_fieldLayout`, skipping the store's layout lookup.
  function load(KeyedRecord memory self) internal view returns (KeyedData memory) {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = RecordMethods.load(
      self.record,
      _fieldLayout
    );
    return _decode(staticData, encodedLengths, dynamicData);
  }

  /// @notice Encode and write the whole record.
  function save(KeyedRecord memory self, KeyedData memory data) internal {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = _encode(data);
    RecordMethods.save(self.record, staticData, encodedLengths, dynamicData, _fieldLayout);
  }

  /// @notice Delete the whole record.
  function destroy(KeyedRecord memory self) internal {
    RecordMethods.destroy(self.record, _fieldLayout);
  }

  /// @notice Handle for the `value` field.
  function value(KeyedRecord memory self) internal pure returns (Uint256Field memory) {
    return Uint256Field(self.record, _fieldLayout, 0);
  }

  /// @notice Encode the key tuple — a primitive for composing direct store calls.
  function _encodeKey(
    uint256 a,
    int32 b,
    address c,
    bool d,
    bytes16 e
  ) internal pure returns (bytes32[] memory keyTuple) {
    keyTuple = new bytes32[](5);
    keyTuple[0] = bytes32(uint256(a));
    keyTuple[1] = bytes32(uint256(int256(b)));
    keyTuple[2] = bytes32(uint256(uint160(c)));
    keyTuple[3] = bytes32(uint256(d ? 1 : 0));
    keyTuple[4] = bytes32(e);
  }

  /// @notice Recover the typed key from a raw keyTuple (e.g. inside a store hook).
  function _decodeKey(
    bytes32[] memory keyTuple
  ) internal pure returns (uint256 a, int32 b, address c, bool d, bytes16 e) {
    a = uint256(uint256(keyTuple[0]));
    b = int32(uint32(uint256(keyTuple[1])));
    c = address(uint160(uint256(keyTuple[2])));
    d = uint256(keyTuple[3]) != 0;
    e = bytes16(keyTuple[4]);
  }

  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](5);
    keyNames[0] = "a";
    keyNames[1] = "b";
    keyNames[2] = "c";
    keyNames[3] = "d";
    keyNames[4] = "e";
  }

  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](1);
    fieldNames[0] = "value";
  }

  /// @notice Register this table. Use the low-level `StoreCore.registerTable` with the
  ///         `_*` constants + name getters to register against a specific store.
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /// @notice Encode `KeyedData` into the store's (static, lengths, dynamic) triple.
  function _encode(KeyedData memory data) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory staticData = abi.encodePacked(data.value);
    return (staticData, EncodedLengths.wrap(bytes32(0)), new bytes(0));
  }

  /// @notice Decode the store's (static, lengths, dynamic) triple into `KeyedData`.
  function _decode(
    bytes memory staticData,
    EncodedLengths encodedLengths,
    bytes memory dynamicData
  ) internal pure returns (KeyedData memory data) {
    data.value = uint256(Bytes.getBytes32(staticData, 0));
  }
}
