// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, RecordMethods } from "../../../src/v3/Record.sol";
import { StoreSwitch } from "../../../src/StoreSwitch.sol";
import { ResourceId } from "../../../src/ResourceId.sol";
import { FieldLayout } from "../../../src/FieldLayout.sol";
import { Schema } from "../../../src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "../../../src/EncodedLengths.sol";
import { Bytes } from "../../../src/Bytes.sol";
import { SliceLib } from "../../../src/Slice.sol";
import { DynamicRange } from "../../../src/v3/fields/_dynamic.sol";
import { EncodeArray } from "../../../src/tightcoder/EncodeArray.sol";
import { Int32Field, Int32FieldLib } from "../../../src/v3/fields/Int32Field.sol";
import { Uint256Field, Uint256FieldLib } from "../../../src/v3/fields/Uint256Field.sol";
import { AddressField, AddressFieldLib } from "../../../src/v3/fields/AddressField.sol";
import { BoolField, BoolFieldLib } from "../../../src/v3/fields/BoolField.sol";
import { StringField, StringFieldLib } from "../../../src/v3/fields/StringField.sol";
import { Uint32ArrayField, Uint32ArrayFieldLib } from "../../../src/v3/fields/Uint32ArrayField.sol";

struct MixedData {
  int32 num;
  uint256 big;
  address owner;
  bool flag;
  string name;
  uint32[] nums;
}

/// @notice The Mixed record at the given key, bound to the canonical table id.
function Mixed(bytes32 id) pure returns (MixedRecord memory) {
  return MixedRecord(Record(MixedRecordMethods._tableId, MixedRecordMethods._encodeKey(id), address(0)));
}

struct MixedRecord {
  Record record;
}

using MixedRecordMethods for MixedRecord global;

library MixedRecordMethods {
  ResourceId constant _tableId = ResourceId.wrap(0x746200000000000000000000000000004d697865640000000000000000000000);
  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0039040204201401000000000000000000000000000000000000000000000000);
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  Schema constant _valueSchema = Schema.wrap(0x00390402231f6160c56500000000000000000000000000000000000000000000);

  /// @notice Operate on a non-canonical table id (e.g. a module's namespaced instance).
  function at(MixedRecord memory self, ResourceId tableId) internal pure returns (MixedRecord memory) {
    self.record.tableId = tableId;
    return self;
  }

  /// @notice Declare this contract's own storage as the store (skips StoreSwitch inference).
  function own(MixedRecord memory self) internal view returns (MixedRecord memory) {
    self.record.store = address(this);
    return self;
  }

  /// @notice Declare an explicit store to read/write.
  function own(MixedRecord memory self, address store) internal pure returns (MixedRecord memory) {
    self.record.store = store;
    return self;
  }

  /// @notice Read the whole record and decode it into a memory struct.
  /// @dev Passes the table's constant `_fieldLayout`, skipping the store's layout lookup.
  function load(MixedRecord memory self) internal view returns (MixedData memory) {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = RecordMethods.load(
      self.record,
      _fieldLayout
    );
    return _decode(staticData, encodedLengths, dynamicData);
  }

  /// @notice Encode and write the whole record.
  function save(MixedRecord memory self, MixedData memory data) internal {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = _encode(data);
    RecordMethods.save(self.record, staticData, encodedLengths, dynamicData, _fieldLayout);
  }

  /// @notice Delete the whole record.
  function destroy(MixedRecord memory self) internal {
    RecordMethods.destroy(self.record, _fieldLayout);
  }

  /// @notice Handle for the `num` field.
  function num(MixedRecord memory self) internal pure returns (Int32Field memory) {
    return Int32Field(self.record, _fieldLayout, 0);
  }

  /// @notice Handle for the `big` field.
  function big(MixedRecord memory self) internal pure returns (Uint256Field memory) {
    return Uint256Field(self.record, _fieldLayout, 1);
  }

  /// @notice Handle for the `owner` field.
  function owner(MixedRecord memory self) internal pure returns (AddressField memory) {
    return AddressField(self.record, _fieldLayout, 2);
  }

  /// @notice Handle for the `flag` field.
  function flag(MixedRecord memory self) internal pure returns (BoolField memory) {
    return BoolField(self.record, _fieldLayout, 3);
  }

  /// @notice Handle for the `name` field.
  function name(MixedRecord memory self) internal pure returns (StringField memory) {
    return StringField(self.record, 0);
  }

  /// @notice Handle for the `nums` field.
  function nums(MixedRecord memory self) internal pure returns (Uint32ArrayField memory) {
    return Uint32ArrayField(self.record, 1);
  }

  /// @notice Encode the key tuple — a primitive for composing direct store calls.
  function _encodeKey(bytes32 id) internal pure returns (bytes32[] memory keyTuple) {
    keyTuple = new bytes32[](1);
    keyTuple[0] = id;
  }

  /// @notice Recover the typed key from a raw keyTuple (e.g. inside a store hook).
  function _decodeKey(bytes32[] memory keyTuple) internal pure returns (bytes32 id) {
    id = keyTuple[0];
  }

  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "id";
  }

  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](6);
    fieldNames[0] = "num";
    fieldNames[1] = "big";
    fieldNames[2] = "owner";
    fieldNames[3] = "flag";
    fieldNames[4] = "name";
    fieldNames[5] = "nums";
  }

  /// @notice Register this table. Use the low-level `StoreCore.registerTable` with the
  ///         `_*` constants + name getters to register against a specific store.
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /// @notice Encode `MixedData` into the store's (static, lengths, dynamic) triple.
  function _encode(MixedData memory data) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory staticData = abi.encodePacked(data.num, data.big, data.owner, data.flag);

    EncodedLengths encodedLengths = EncodedLengthsLib.pack(bytes(data.name).length, data.nums.length * 4);
    bytes memory dynamicData = abi.encodePacked(bytes(data.name), EncodeArray.encode(data.nums));
    return (staticData, encodedLengths, dynamicData);
  }

  /// @notice Decode the store's (static, lengths, dynamic) triple into `MixedData`.
  function _decode(
    bytes memory staticData,
    EncodedLengths encodedLengths,
    bytes memory dynamicData
  ) internal pure returns (MixedData memory data) {
    data.num = int32(uint32(Bytes.getBytes4(staticData, 0)));
    data.big = uint256(Bytes.getBytes32(staticData, 4));
    data.owner = address(uint160(Bytes.getBytes20(staticData, 36)));
    data.flag = uint8(Bytes.getBytes1(staticData, 56)) != 0;

    (uint256 _start0, uint256 _end0) = DynamicRange.range(encodedLengths, 0);
    data.name = string(SliceLib.getSubslice(dynamicData, _start0, _end0).toBytes());

    (uint256 _start1, uint256 _end1) = DynamicRange.range(encodedLengths, 1);
    data.nums = SliceLib.getSubslice(dynamicData, _start1, _end1).decodeArray_uint32();
  }
}
