// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, RecordMethods } from "../../../src/v3/Record.sol";
import { ResourceId } from "../../../src/ResourceId.sol";
import { FieldLayout } from "../../../src/FieldLayout.sol";
import { Schema } from "../../../src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "../../../src/EncodedLengths.sol";
import { Int32Field, Int32FieldLib } from "../../../src/v3/fields/Int32Field.sol";
import { Uint256Field, Uint256FieldLib } from "../../../src/v3/fields/Uint256Field.sol";
import { AddressField, AddressFieldLib } from "../../../src/v3/fields/AddressField.sol";
import { BoolField, BoolFieldLib } from "../../../src/v3/fields/BoolField.sol";
import { StringField, StringFieldLib } from "../../../src/v3/fields/StringField.sol";
import { Uint32ArrayField, Uint32ArrayFieldLib } from "../../../src/v3/fields/Uint32ArrayField.sol";

struct MixedData {
  int32 num;
  uint256 big;
  address owner;
  bool flag;
  string name;
  uint32[] nums;
}

/// @notice The Mixed record at the given key, bound to the canonical table id.
function Mixed(bytes32 id) pure returns (MixedRecord memory) {
  bytes32[] memory keyTuple = new bytes32[](1);
  keyTuple[0] = id;
  return MixedRecord(Record(MixedRecordMethods._tableId, keyTuple, address(0)));
}

struct MixedRecord {
  Record record;
}

using MixedRecordMethods for MixedRecord global;

library MixedRecordMethods {
  ResourceId constant _tableId = ResourceId.wrap(0x746200000000000000000000000000004d697865640000000000000000000000);
  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0039040204201401000000000000000000000000000000000000000000000000);
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  Schema constant _valueSchema = Schema.wrap(0x00390402231f6160c56500000000000000000000000000000000000000000000);

  /// @notice Operate on a non-canonical table id (e.g. a module's namespaced instance).
  function at(MixedRecord memory self, ResourceId tableId) internal pure returns (MixedRecord memory) {
    self.record.tableId = tableId;
    return self;
  }

  /// @notice Declare this contract's own storage as the store (skips StoreSwitch inference).
  function own(MixedRecord memory self) internal view returns (MixedRecord memory) {
    self.record.store = address(this);
    return self;
  }

  /// @notice Declare an explicit store to read/write.
  function own(MixedRecord memory self, address store) internal pure returns (MixedRecord memory) {
    self.record.store = store;
    return self;
  }

  /// @notice Read the whole record and decode it into a memory struct.
  function load(MixedRecord memory self) internal view returns (MixedData memory) {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = RecordMethods.load(
      self.record
    );
    return _decode(staticData, encodedLengths, dynamicData);
  }

  /// @notice Encode and write the whole record.
  function save(MixedRecord memory self, MixedData memory data) internal {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = _encode(data);
    RecordMethods.save(self.record, staticData, encodedLengths, dynamicData);
  }

  /// @notice Delete the whole record.
  function destroy(MixedRecord memory self) internal {
    RecordMethods.destroy(self.record);
  }

  /// @notice Handle for the `num` field.
  function num(MixedRecord memory self) internal pure returns (Int32Field memory) {
    return Int32Field(self.record, _fieldLayout, 0);
  }

  /// @notice Handle for the `big` field.
  function big(MixedRecord memory self) internal pure returns (Uint256Field memory) {
    return Uint256Field(self.record, _fieldLayout, 1);
  }

  /// @notice Handle for the `owner` field.
  function owner(MixedRecord memory self) internal pure returns (AddressField memory) {
    return AddressField(self.record, _fieldLayout, 2);
  }

  /// @notice Handle for the `flag` field.
  function flag(MixedRecord memory self) internal pure returns (BoolField memory) {
    return BoolField(self.record, _fieldLayout, 3);
  }

  /// @notice Handle for the `name` field.
  function name(MixedRecord memory self) internal pure returns (StringField memory) {
    return StringField(self.record, 0);
  }

  /// @notice Handle for the `nums` field.
  function nums(MixedRecord memory self) internal pure returns (Uint32ArrayField memory) {
    return Uint32ArrayField(self.record, 1);
  }

  /// @notice Encode `MixedData` into the store's (static, lengths, dynamic) triple.
  function _encode(MixedData memory data) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory staticData = abi.encodePacked(
      Int32FieldLib.encode(data.num),
      Uint256FieldLib.encode(data.big),
      AddressFieldLib.encode(data.owner),
      BoolFieldLib.encode(data.flag)
    );

    EncodedLengths encodedLengths = EncodedLengthsLib.pack(
      StringFieldLib.byteLength(data.name),
      Uint32ArrayFieldLib.byteLength(data.nums)
    );
    bytes memory dynamicData = abi.encodePacked(
      StringFieldLib.encode(data.name),
      Uint32ArrayFieldLib.encode(data.nums)
    );
    return (staticData, encodedLengths, dynamicData);
  }

  /// @notice Decode the store's (static, lengths, dynamic) triple into `MixedData`.
  function _decode(
    bytes memory staticData,
    EncodedLengths encodedLengths,
    bytes memory dynamicData
  ) internal pure returns (MixedData memory data) {
    data.num = Int32FieldLib.decode(staticData, 0);
    data.big = Uint256FieldLib.decode(staticData, 4);
    data.owner = AddressFieldLib.decode(staticData, 36);
    data.flag = BoolFieldLib.decode(staticData, 56);
    data.name = StringFieldLib.decode(dynamicData, encodedLengths, 0);
    data.nums = Uint32ArrayFieldLib.decode(dynamicData, encodedLengths, 1);
  }
}
