// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Bytes32Field, Bytes32FieldLib } from "../../../src/v3/fields/Bytes32Field.sol";
import { MyId } from "../MyId.sol";

/// @notice A handle to one `MyId` field (a user type wrapping `bytes32`).
struct MyIdField {
  Bytes32Field inner;
}

using MyIdFieldLib for MyIdField global;

/// @notice The `MyId` field codec: delegates to `Bytes32FieldLib`, wrapping/unwrapping the UDVT.
library MyIdFieldLib {
  function load(MyIdField memory self) internal view returns (MyId) {
    return MyId.wrap(self.inner.load());
  }

  function save(MyIdField memory self, MyId value) internal {
    self.inner.save(MyId.unwrap(value));
  }

  function encode(MyId value) internal pure returns (bytes memory) {
    return Bytes32FieldLib.encode(MyId.unwrap(value));
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (MyId) {
    return MyId.wrap(Bytes32FieldLib.decode(staticData, offset));
  }
}
