// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, RecordMethods } from "../../../src/v3/Record.sol";
import { StoreSwitch } from "../../../src/StoreSwitch.sol";
import { ResourceId } from "../../../src/ResourceId.sol";
import { FieldLayout } from "../../../src/FieldLayout.sol";
import { Schema } from "../../../src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "../../../src/EncodedLengths.sol";
import { Bytes } from "../../../src/Bytes.sol";

import { Uint256Field, Uint256FieldLib } from "../../../src/v3/fields/Uint256Field.sol";
import { Bytes32Field } from "../../../src/v3/fields/Bytes32Field.sol";
import { MyIdField, MyIdFieldLib } from "./MyIdField.sol";
import { MyId } from "../MyId.sol";

struct OwnedData {
  MyId owner;
  uint256 score;
}

/// @notice The Owned record at the given key, bound to the canonical table id.
function Owned(MyId entity) pure returns (OwnedRecord memory) {
  return OwnedRecord(Record(OwnedRecordMethods._tableId, OwnedRecordMethods._encodeKey(entity), address(0)));
}

struct OwnedRecord {
  Record record;
}

using OwnedRecordMethods for OwnedRecord global;

library OwnedRecordMethods {
  ResourceId constant _tableId = ResourceId.wrap(0x746200000000000000000000000000004f776e65640000000000000000000000);
  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0040020020200000000000000000000000000000000000000000000000000000);
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  Schema constant _valueSchema = Schema.wrap(0x004002005f1f0000000000000000000000000000000000000000000000000000);

  /// @notice Operate on a non-canonical table id (e.g. a module's namespaced instance).
  function at(OwnedRecord memory self, ResourceId tableId) internal pure returns (OwnedRecord memory) {
    self.record.tableId = tableId;
    return self;
  }

  /// @notice Declare this contract's own storage as the store (skips StoreSwitch inference).
  function own(OwnedRecord memory self) internal view returns (OwnedRecord memory) {
    self.record.store = address(this);
    return self;
  }

  /// @notice Declare an explicit store to read/write.
  function own(OwnedRecord memory self, address store) internal pure returns (OwnedRecord memory) {
    self.record.store = store;
    return self;
  }

  /// @notice Read the whole record and decode it into a memory struct.
  /// @dev Passes the table's constant `_fieldLayout`, skipping the store's layout lookup.
  function load(OwnedRecord memory self) internal view returns (OwnedData memory) {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = RecordMethods.load(
      self.record,
      _fieldLayout
    );
    return _decode(staticData, encodedLengths, dynamicData);
  }

  /// @notice Encode and write the whole record.
  function save(OwnedRecord memory self, OwnedData memory data) internal {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = _encode(data);
    RecordMethods.save(self.record, staticData, encodedLengths, dynamicData, _fieldLayout);
  }

  /// @notice Delete the whole record.
  function destroy(OwnedRecord memory self) internal {
    RecordMethods.destroy(self.record, _fieldLayout);
  }

  /// @notice Handle for the `owner` field.
  function owner(OwnedRecord memory self) internal pure returns (MyIdField memory) {
    return MyIdField(Bytes32Field(self.record, _fieldLayout, 0));
  }

  /// @notice Handle for the `score` field.
  function score(OwnedRecord memory self) internal pure returns (Uint256Field memory) {
    return Uint256Field(self.record, _fieldLayout, 1);
  }

  /// @notice Encode the key tuple — a primitive for composing direct store calls.
  function _encodeKey(MyId entity) internal pure returns (bytes32[] memory keyTuple) {
    keyTuple = new bytes32[](1);
    keyTuple[0] = MyId.unwrap(entity);
  }

  /// @notice Recover the typed key from a raw keyTuple (e.g. inside a store hook).
  function _decodeKey(bytes32[] memory keyTuple) internal pure returns (MyId entity) {
    entity = MyId.wrap(keyTuple[0]);
  }

  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "entity";
  }

  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "owner";
    fieldNames[1] = "score";
  }

  /// @notice Register this table. Use the low-level `StoreCore.registerTable` with the
  ///         `_*` constants + name getters to register against a specific store.
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /// @notice Encode `OwnedData` into the store's (static, lengths, dynamic) triple.
  function _encode(OwnedData memory data) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory staticData = abi.encodePacked(MyId.unwrap(data.owner), data.score);
    return (staticData, EncodedLengths.wrap(bytes32(0)), new bytes(0));
  }

  /// @notice Decode the store's (static, lengths, dynamic) triple into `OwnedData`.
  function _decode(
    bytes memory staticData,
    EncodedLengths encodedLengths,
    bytes memory dynamicData
  ) internal pure returns (OwnedData memory data) {
    data.owner = MyId.wrap(Bytes.getBytes32(staticData, 0));
    data.score = uint256(Bytes.getBytes32(staticData, 32));
  }
}
