// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Bytes32Field, Bytes32FieldLib } from "../../../src/v3/fields/Bytes32Field.sol";
import { ResourceId } from "../../../src/ResourceId.sol";

/// @notice A handle to one `ResourceId` field (a UDVT over `bytes32`).
struct ResourceIdField {
  Bytes32Field inner;
}

using ResourceIdFieldLib for ResourceIdField global;

/// @notice The `ResourceId` field codec: delegates to `Bytes32FieldLib`, converting at the boundary.
library ResourceIdFieldLib {
  function load(ResourceIdField memory self) internal view returns (ResourceId) {
    return ResourceId.wrap(self.inner.load());
  }

  function save(ResourceIdField memory self, ResourceId value) internal {
    self.inner.save(ResourceId.unwrap(value));
  }

  function encode(ResourceId value) internal pure returns (bytes memory) {
    return Bytes32FieldLib.encode(ResourceId.unwrap(value));
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (ResourceId) {
    return ResourceId.wrap(Bytes32FieldLib.decode(staticData, offset));
  }
}
