// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Bytes32Field, Bytes32FieldLib } from "../../../src/fields/Bytes32Field.sol";
import { Schema } from "../../../src/Schema.sol";

/// @notice A handle to one `Schema` field (a UDVT over `bytes32`).
struct SchemaField {
  Bytes32Field inner;
}

using SchemaFieldLib for SchemaField global;

/// @notice The `Schema` field codec: delegates to `Bytes32FieldLib`, converting at the boundary.
library SchemaFieldLib {
  function load(SchemaField memory self) internal view returns (Schema) {
    return Schema.wrap(self.inner.load());
  }

  function save(SchemaField memory self, Schema value) internal {
    self.inner.save(Schema.unwrap(value));
  }

  function encode(Schema value) internal pure returns (bytes memory) {
    return Bytes32FieldLib.encode(Schema.unwrap(value));
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (Schema) {
    return Schema.wrap(Bytes32FieldLib.decode(staticData, offset));
  }
}
