import { code } from "./render";
import { TableCodegen, StaticField, DynamicField } from "./types";

/**
 * Render a complete v3 table file.
 *
 * Read this function top to bottom and you are reading the generated file top
 * to bottom: header, imports, the data struct, the entry functions, then the
 * methods library. Each section below is a small pure function returning the
 * Solidity for exactly that part — there are no variant cross-products, no
 * callbacks, and no per-type casting logic (that all lives in the shared
 * runtime libraries the output imports). Output is prettier-formatted, so these
 * templates are written for reading, not layout.
 */
export function renderTable(table: TableCodegen): string {
  const lib = `${table.label}RecordMethods`;
  const staticFields = table.fields.filter((field): field is StaticField => field.kind === "static");
  const dynamicFields = table.fields.filter((field): field is DynamicField => field.kind === "dynamic");

  return code`
    // SPDX-License-Identifier: MIT
    pragma solidity >=0.8.24;

    /* Autogenerated file. Do not edit manually. */

    ${renderImports(table)}

    ${renderDataStruct(table)}

    ${renderEntryFunctions(table, lib)}

    struct ${table.label}Record {
      Record record;
    }

    using ${lib} for ${table.label}Record global;

    library ${lib} {
      ${renderConstants(table)}

      ${renderModifiers(table)}

      ${renderRecordMethods(table)}

      ${table.fields.map((field) => renderFieldAccessor(field, table))}

      ${renderCodec(table, staticFields, dynamicFields)}
    }
  `;
}

// ─────────────────────────────────────────────────────────────────────────────
// imports
// ─────────────────────────────────────────────────────────────────────────────

function renderImports(table: TableCodegen): string {
  const runtime = (symbols: string, file: string) => `import { ${symbols} } from "${table.storeImportPath}/${file}";`;

  // One handle type per distinct ABI type used by a field, imported from the runtime.
  const fieldHandles = [...new Set(table.fields.map((field) => field.type.fieldHandle))];

  return code`
    ${runtime("Record, RecordMethods", "v3/Record.sol")}
    ${runtime("ResourceId", "ResourceId.sol")}
    ${runtime("FieldLayout", "FieldLayout.sol")}
    ${runtime("Schema", "Schema.sol")}
    ${runtime("EncodedLengths, EncodedLengthsLib", "EncodedLengths.sol")}
    ${fieldHandles.map((handle) => runtime(`${handle}, ${handle}Lib`, `v3/fields/${handle}.sol`))}
    ${table.imports.map(({ symbol, path }) => `import { ${symbol} } from "${path}";`)}
  `;
}

// ─────────────────────────────────────────────────────────────────────────────
// data struct: the plain, mutable in-memory record
// ─────────────────────────────────────────────────────────────────────────────

function renderDataStruct(table: TableCodegen): string {
  return code`
    struct ${table.dataStruct} {
      ${table.fields.map((field) => `${field.typeName} ${field.name};`)}
    }
  `;
}

// ─────────────────────────────────────────────────────────────────────────────
// entry functions: Position(key...) -> record handle, Position() -> table handle
// ─────────────────────────────────────────────────────────────────────────────

function renderEntryFunctions(table: TableCodegen, lib: string): string {
  const params = table.keyFields.map((key) => `${key.typeName} ${key.name}`).join(", ");

  return code`
    /// @notice The ${table.label} record at the given key, bound to the canonical table id.
    function ${table.label}(${params}) pure returns (${table.label}Record memory) {
      bytes32[] memory keyTuple = new bytes32[](${table.keyFields.length});
      ${table.keyFields.map((key, index) => `keyTuple[${index}] = ${key.toBytes32};`)}
      return ${table.label}Record(Record(${lib}._tableId, keyTuple, address(0)));
    }
  `;
}

// ─────────────────────────────────────────────────────────────────────────────
// constants: precomputed, never derived in Solidity
// ─────────────────────────────────────────────────────────────────────────────

function renderConstants(table: TableCodegen): string {
  return code`
    ResourceId constant _tableId = ResourceId.wrap(${table.tableId});
    FieldLayout constant _fieldLayout = FieldLayout.wrap(${table.fieldLayout});
    Schema constant _keySchema = Schema.wrap(${table.keySchema});
    Schema constant _valueSchema = Schema.wrap(${table.valueSchema});
  `;
}

// ─────────────────────────────────────────────────────────────────────────────
// dispatch + table-id modifiers (chainable; mutate the handle's Record in place)
// ─────────────────────────────────────────────────────────────────────────────

function renderModifiers(table: TableCodegen): string {
  const Self = `${table.label}Record`;
  return code`
    /// @notice Operate on a non-canonical table id (e.g. a module's namespaced instance).
    function at(${Self} memory self, ResourceId tableId) internal pure returns (${Self} memory) {
      self.record.tableId = tableId;
      return self;
    }

    /// @notice Declare this contract's own storage as the store (skips StoreSwitch inference).
    function own(${Self} memory self) internal view returns (${Self} memory) {
      self.record.store = address(this);
      return self;
    }

    /// @notice Declare an explicit store to read/write.
    function own(${Self} memory self, address store) internal pure returns (${Self} memory) {
      self.record.store = store;
      return self;
    }
  `;
}

// ─────────────────────────────────────────────────────────────────────────────
// record methods: load / save / destroy (delegate to the shared RecordMethods)
// ─────────────────────────────────────────────────────────────────────────────

function renderRecordMethods(table: TableCodegen): string {
  const Self = `${table.label}Record`;
  return code`
    /// @notice Read the whole record and decode it into a memory struct.
    function load(${Self} memory self) internal view returns (${table.dataStruct} memory) {
      (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) =
        RecordMethods.load(self.record, _fieldLayout);
      return _decode(staticData, encodedLengths, dynamicData);
    }

    /// @notice Encode and write the whole record.
    function save(${Self} memory self, ${table.dataStruct} memory data) internal {
      (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = _encode(data);
      RecordMethods.save(self.record, _fieldLayout, staticData, encodedLengths, dynamicData);
    }

    /// @notice Delete the whole record.
    function destroy(${Self} memory self) internal {
      RecordMethods.destroy(self.record, _fieldLayout);
    }
  `;
}

// ─────────────────────────────────────────────────────────────────────────────
// field accessors: one line each, returning a typed field handle
// ─────────────────────────────────────────────────────────────────────────────

function renderFieldAccessor(field: StaticField | DynamicField, table: TableCodegen): string {
  const Self = `${table.label}Record`;
  const handle = field.type.fieldHandle;

  // Static handles carry (record, fieldLayout, schemaIndex); dynamic carry (record, dynamicIndex).
  const construct =
    field.kind === "static"
      ? `${handle}(self.record, _fieldLayout, ${field.schemaIndex})`
      : `${handle}(self.record, ${field.dynamicIndex})`;

  return code`
    /// @notice Handle for the \`${field.name}\` field.
    function ${field.name}(${Self} memory self) internal pure returns (${handle} memory) {
      return ${construct};
    }
  `;
}

// ─────────────────────────────────────────────────────────────────────────────
// record codec: the only genuinely shape-specific code. Per-field encode/decode
// delegates to the shared field libs, so casts live there, not here.
// ─────────────────────────────────────────────────────────────────────────────

function renderCodec(
  table: TableCodegen,
  staticFields: readonly StaticField[],
  dynamicFields: readonly DynamicField[],
): string {
  return code`
    /// @notice Encode \`${table.dataStruct}\` into the store's (static, lengths, dynamic) triple.
    function _encode(${table.dataStruct} memory data)
      internal
      pure
      returns (bytes memory, EncodedLengths, bytes memory)
    {
      bytes memory staticData = abi.encodePacked(
        ${staticFields.map((field) => `${field.type.fieldHandle}Lib.encode(data.${field.name})`).join(",\n")}
      );
      ${
        dynamicFields.length === 0
          ? code`return (staticData, EncodedLengths.wrap(bytes32(0)), new bytes(0));`
          : code`
            EncodedLengths encodedLengths = EncodedLengthsLib.pack(
              ${dynamicFields.map((field) => `${field.type.fieldHandle}Lib.byteLength(data.${field.name})`).join(",\n")}
            );
            bytes memory dynamicData = abi.encodePacked(
              ${dynamicFields.map((field) => `${field.type.fieldHandle}Lib.encode(data.${field.name})`).join(",\n")}
            );
            return (staticData, encodedLengths, dynamicData);
          `
      }
    }

    /// @notice Decode the store's (static, lengths, dynamic) triple into \`${table.dataStruct}\`.
    function _decode(bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData)
      internal
      pure
      returns (${table.dataStruct} memory data)
    {
      ${staticFields.map(
        (field) => `data.${field.name} = ${field.type.fieldHandle}Lib.decode(staticData, ${field.byteOffset});`,
      )}
      ${dynamicFields.map(
        (field) =>
          `data.${field.name} = ${field.type.fieldHandle}Lib.decode(dynamicData, encodedLengths, ${field.dynamicIndex});`,
      )}
    }
  `;
}
