import { code } from "./render";

/**
 * Renders the Solidity declaration for a config-declared enum.
 *
 * The `enums` config section is the full-stack source of truth (Solidity type + on-chain `uint8`
 * schema + TS client variants), so codegen authors the declaration — the user never hand-writes it,
 * matching how tables are generated from config. The matching field handle is produced by
 * `renderUserTypeField` (an enum is a user type over `uint8`).
 */
export function renderEnum(name: string, variants: readonly string[]): string {
  return code`
    // SPDX-License-Identifier: MIT
    pragma solidity >=0.8.24;

    /* Autogenerated file. Do not edit manually. */

    enum ${name} {
      ${variants.join(",\n  ")}
    }
  `;
}
