// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `bytes27` field of a record.
struct Bytes27Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes27FieldLib for Bytes27Field global;

/// @notice The `bytes27` field codec, shared by every `bytes27` field of every table.
library Bytes27FieldLib {
  function load(Bytes27Field memory self) internal view returns (bytes27) {
    return bytes27(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes27Field memory self, bytes27 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes27 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes27) {
    return Bytes.getBytes27(staticData, offset);
  }
}
