// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `bytes10` field of a record.
struct Bytes10Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes10FieldLib for Bytes10Field global;

/// @notice The `bytes10` field codec, shared by every `bytes10` field of every table.
library Bytes10FieldLib {
  function load(Bytes10Field memory self) internal view returns (bytes10) {
    return bytes10(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes10Field memory self, bytes10 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes10 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes10) {
    return Bytes.getBytes10(staticData, offset);
  }
}
