// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `bytes5` field of a record.
struct Bytes5Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes5FieldLib for Bytes5Field global;

/// @notice The `bytes5` field codec, shared by every `bytes5` field of every table.
library Bytes5FieldLib {
  function load(Bytes5Field memory self) internal view returns (bytes5) {
    return bytes5(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes5Field memory self, bytes5 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes5 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes5) {
    return Bytes.getBytes5(staticData, offset);
  }
}
