// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `bytes24` field of a record.
struct Bytes24Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes24FieldLib for Bytes24Field global;

/// @notice The `bytes24` field codec, shared by every `bytes24` field of every table.
library Bytes24FieldLib {
  function load(Bytes24Field memory self) internal view returns (bytes24) {
    return bytes24(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes24Field memory self, bytes24 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes24 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes24) {
    return Bytes.getBytes24(staticData, offset);
  }
}
