// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `bytes20` field of a record.
struct Bytes20Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes20FieldLib for Bytes20Field global;

/// @notice The `bytes20` field codec, shared by every `bytes20` field of every table.
library Bytes20FieldLib {
  function load(Bytes20Field memory self) internal view returns (bytes20) {
    return bytes20(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes20Field memory self, bytes20 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes20 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes20) {
    return Bytes.getBytes20(staticData, offset);
  }
}
