// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `bytes2` field of a record.
struct Bytes2Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes2FieldLib for Bytes2Field global;

/// @notice The `bytes2` field codec, shared by every `bytes2` field of every table.
library Bytes2FieldLib {
  function load(Bytes2Field memory self) internal view returns (bytes2) {
    return bytes2(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes2Field memory self, bytes2 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes2 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes2) {
    return Bytes.getBytes2(staticData, offset);
  }
}
