// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `bytes26` field of a record.
struct Bytes26Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes26FieldLib for Bytes26Field global;

/// @notice The `bytes26` field codec, shared by every `bytes26` field of every table.
library Bytes26FieldLib {
  function load(Bytes26Field memory self) internal view returns (bytes26) {
    return bytes26(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes26Field memory self, bytes26 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes26 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes26) {
    return Bytes.getBytes26(staticData, offset);
  }
}
