// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `bytes19` field of a record.
struct Bytes19Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes19FieldLib for Bytes19Field global;

/// @notice The `bytes19` field codec, shared by every `bytes19` field of every table.
library Bytes19FieldLib {
  function load(Bytes19Field memory self) internal view returns (bytes19) {
    return bytes19(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes19Field memory self, bytes19 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes19 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes19) {
    return Bytes.getBytes19(staticData, offset);
  }
}
