// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `bytes18` field of a record.
struct Bytes18Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes18FieldLib for Bytes18Field global;

/// @notice The `bytes18` field codec, shared by every `bytes18` field of every table.
library Bytes18FieldLib {
  function load(Bytes18Field memory self) internal view returns (bytes18) {
    return bytes18(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes18Field memory self, bytes18 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes18 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes18) {
    return Bytes.getBytes18(staticData, offset);
  }
}
