// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `bytes4` field of a record.
struct Bytes4Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes4FieldLib for Bytes4Field global;

/// @notice The `bytes4` field codec, shared by every `bytes4` field of every table.
library Bytes4FieldLib {
  function load(Bytes4Field memory self) internal view returns (bytes4) {
    return bytes4(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes4Field memory self, bytes4 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes4 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes4) {
    return Bytes.getBytes4(staticData, offset);
  }
}
