// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `bytes3` field of a record.
struct Bytes3Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes3FieldLib for Bytes3Field global;

/// @notice The `bytes3` field codec, shared by every `bytes3` field of every table.
library Bytes3FieldLib {
  function load(Bytes3Field memory self) internal view returns (bytes3) {
    return bytes3(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes3Field memory self, bytes3 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes3 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes3) {
    return Bytes.getBytes3(staticData, offset);
  }
}
