// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `bytes11` field of a record.
struct Bytes11Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes11FieldLib for Bytes11Field global;

/// @notice The `bytes11` field codec, shared by every `bytes11` field of every table.
library Bytes11FieldLib {
  function load(Bytes11Field memory self) internal view returns (bytes11) {
    return bytes11(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes11Field memory self, bytes11 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes11 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes11) {
    return Bytes.getBytes11(staticData, offset);
  }
}
