// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `bytes8` field of a record.
struct Bytes8Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes8FieldLib for Bytes8Field global;

/// @notice The `bytes8` field codec, shared by every `bytes8` field of every table.
library Bytes8FieldLib {
  function load(Bytes8Field memory self) internal view returns (bytes8) {
    return bytes8(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes8Field memory self, bytes8 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes8 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes8) {
    return Bytes.getBytes8(staticData, offset);
  }
}
