// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `bytes9` field of a record.
struct Bytes9Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes9FieldLib for Bytes9Field global;

/// @notice The `bytes9` field codec, shared by every `bytes9` field of every table.
library Bytes9FieldLib {
  function load(Bytes9Field memory self) internal view returns (bytes9) {
    return bytes9(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes9Field memory self, bytes9 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes9 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes9) {
    return Bytes.getBytes9(staticData, offset);
  }
}
