// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `bytes12` field of a record.
struct Bytes12Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Bytes12FieldLib for Bytes12Field global;

/// @notice The `bytes12` field codec, shared by every `bytes12` field of every table.
library Bytes12FieldLib {
  function load(Bytes12Field memory self) internal view returns (bytes12) {
    return bytes12(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout));
  }

  function save(Bytes12Field memory self, bytes12 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(bytes12 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (bytes12) {
    return Bytes.getBytes12(staticData, offset);
  }
}
