// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `int112` field of a record.
struct Int112Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int112FieldLib for Int112Field global;

/// @notice The `int112` field codec, shared by every `int112` field of every table.
library Int112FieldLib {
  function load(Int112Field memory self) internal view returns (int112) {
    return int112(uint112(bytes14(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int112Field memory self, int112 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int112 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int112) {
    return int112(uint112(Bytes.getBytes14(staticData, offset)));
  }
}
