// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `int176` field of a record.
struct Int176Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int176FieldLib for Int176Field global;

/// @notice The `int176` field codec, shared by every `int176` field of every table.
library Int176FieldLib {
  function load(Int176Field memory self) internal view returns (int176) {
    return int176(uint176(bytes22(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int176Field memory self, int176 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int176 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int176) {
    return int176(uint176(Bytes.getBytes22(staticData, offset)));
  }
}
