// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `int160` field of a record.
struct Int160Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int160FieldLib for Int160Field global;

/// @notice The `int160` field codec, shared by every `int160` field of every table.
library Int160FieldLib {
  function load(Int160Field memory self) internal view returns (int160) {
    return int160(uint160(bytes20(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int160Field memory self, int160 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int160 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int160) {
    return int160(uint160(Bytes.getBytes20(staticData, offset)));
  }
}
