// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `int152` field of a record.
struct Int152Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int152FieldLib for Int152Field global;

/// @notice The `int152` field codec, shared by every `int152` field of every table.
library Int152FieldLib {
  function load(Int152Field memory self) internal view returns (int152) {
    return int152(uint152(bytes19(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int152Field memory self, int152 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int152 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int152) {
    return int152(uint152(Bytes.getBytes19(staticData, offset)));
  }
}
