// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `int168` field of a record.
struct Int168Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int168FieldLib for Int168Field global;

/// @notice The `int168` field codec, shared by every `int168` field of every table.
library Int168FieldLib {
  function load(Int168Field memory self) internal view returns (int168) {
    return int168(uint168(bytes21(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int168Field memory self, int168 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int168 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int168) {
    return int168(uint168(Bytes.getBytes21(staticData, offset)));
  }
}
