// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `int208` field of a record.
struct Int208Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int208FieldLib for Int208Field global;

/// @notice The `int208` field codec, shared by every `int208` field of every table.
library Int208FieldLib {
  function load(Int208Field memory self) internal view returns (int208) {
    return int208(uint208(bytes26(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int208Field memory self, int208 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int208 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int208) {
    return int208(uint208(Bytes.getBytes26(staticData, offset)));
  }
}
