// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `int248` field of a record.
struct Int248Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int248FieldLib for Int248Field global;

/// @notice The `int248` field codec, shared by every `int248` field of every table.
library Int248FieldLib {
  function load(Int248Field memory self) internal view returns (int248) {
    return int248(uint248(bytes31(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int248Field memory self, int248 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int248 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int248) {
    return int248(uint248(Bytes.getBytes31(staticData, offset)));
  }
}
