// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `int216` field of a record.
struct Int216Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int216FieldLib for Int216Field global;

/// @notice The `int216` field codec, shared by every `int216` field of every table.
library Int216FieldLib {
  function load(Int216Field memory self) internal view returns (int216) {
    return int216(uint216(bytes27(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int216Field memory self, int216 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int216 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int216) {
    return int216(uint216(Bytes.getBytes27(staticData, offset)));
  }
}
