// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `int224` field of a record.
struct Int224Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int224FieldLib for Int224Field global;

/// @notice The `int224` field codec, shared by every `int224` field of every table.
library Int224FieldLib {
  function load(Int224Field memory self) internal view returns (int224) {
    return int224(uint224(bytes28(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int224Field memory self, int224 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int224 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int224) {
    return int224(uint224(Bytes.getBytes28(staticData, offset)));
  }
}
