// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `int232` field of a record.
struct Int232Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int232FieldLib for Int232Field global;

/// @notice The `int232` field codec, shared by every `int232` field of every table.
library Int232FieldLib {
  function load(Int232Field memory self) internal view returns (int232) {
    return int232(uint232(bytes29(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int232Field memory self, int232 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int232 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int232) {
    return int232(uint232(Bytes.getBytes29(staticData, offset)));
  }
}
