// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { EncodedLengths } from "../EncodedLengths.sol";
import { SliceLib } from "../Slice.sol";
import { EncodeArray } from "../tightcoder/EncodeArray.sol";
import { DynamicRange } from "./_dynamic.sol";

/// @notice A handle to one `int56[]` field of a record.
struct Int56ArrayField {
  Record record;
  uint8 dynamicIndex;
}

using Int56ArrayFieldLib for Int56ArrayField global;

/// @notice The `int56[]` field codec, shared by every `int56[]` field of every table.
library Int56ArrayFieldLib {
  uint256 constant _ELEMENT_SIZE = 7;

  function load(Int56ArrayField memory self) internal view returns (int56[] memory) {
    bytes memory blob = StoreAccess.getDynamicField(self.record, self.dynamicIndex);
    return SliceLib.getSubslice(blob, 0, blob.length).decodeArray_int56();
  }

  function save(Int56ArrayField memory self, int56[] memory value) internal {
    StoreAccess.setDynamicField(self.record, self.dynamicIndex, EncodeArray.encode(value));
  }

  /// @notice Number of elements.
  function length(Int56ArrayField memory self) internal view returns (uint256) {
    return StoreAccess.getDynamicFieldLength(self.record, self.dynamicIndex) / _ELEMENT_SIZE;
  }

  /// @notice Load one element by index.
  function load(Int56ArrayField memory self, uint256 index) internal view returns (int56) {
    bytes memory blob = StoreAccess.getDynamicFieldSlice(
      self.record,
      self.dynamicIndex,
      index * _ELEMENT_SIZE,
      (index + 1) * _ELEMENT_SIZE
    );
    return int56(uint56(bytes7(blob)));
  }

  /// @notice Overwrite one element by index.
  function save(Int56ArrayField memory self, uint256 index, int56 element) internal {
    StoreAccess.spliceDynamicData(
      self.record,
      self.dynamicIndex,
      uint40(index * _ELEMENT_SIZE),
      uint40(_ELEMENT_SIZE),
      abi.encodePacked(element)
    );
  }

  function push(Int56ArrayField memory self, int56 element) internal {
    StoreAccess.pushToDynamicField(self.record, self.dynamicIndex, abi.encodePacked(element));
  }

  function pop(Int56ArrayField memory self) internal {
    StoreAccess.popFromDynamicField(self.record, self.dynamicIndex, _ELEMENT_SIZE);
  }

  function encode(int56[] memory value) internal pure returns (bytes memory) {
    return EncodeArray.encode(value);
  }

  function byteLength(int56[] memory value) internal pure returns (uint256) {
    return value.length * _ELEMENT_SIZE;
  }

  function decode(
    bytes memory dynamicData,
    EncodedLengths encodedLengths,
    uint8 dynamicIndex
  ) internal pure returns (int56[] memory) {
    (uint256 start, uint256 end) = DynamicRange.range(encodedLengths, dynamicIndex);
    return SliceLib.getSubslice(dynamicData, start, end).decodeArray_int56();
  }
}
