// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `int64` field of a record.
struct Int64Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int64FieldLib for Int64Field global;

/// @notice The `int64` field codec, shared by every `int64` field of every table.
library Int64FieldLib {
  function load(Int64Field memory self) internal view returns (int64) {
    return int64(uint64(bytes8(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int64Field memory self, int64 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int64 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int64) {
    return int64(uint64(Bytes.getBytes8(staticData, offset)));
  }
}
