// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `int72` field of a record.
struct Int72Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int72FieldLib for Int72Field global;

/// @notice The `int72` field codec, shared by every `int72` field of every table.
library Int72FieldLib {
  function load(Int72Field memory self) internal view returns (int72) {
    return int72(uint72(bytes9(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int72Field memory self, int72 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int72 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int72) {
    return int72(uint72(Bytes.getBytes9(staticData, offset)));
  }
}
