// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `int80` field of a record.
struct Int80Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int80FieldLib for Int80Field global;

/// @notice The `int80` field codec, shared by every `int80` field of every table.
library Int80FieldLib {
  function load(Int80Field memory self) internal view returns (int80) {
    return int80(uint80(bytes10(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int80Field memory self, int80 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int80 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int80) {
    return int80(uint80(Bytes.getBytes10(staticData, offset)));
  }
}
