// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `int8` field of a record.
struct Int8Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int8FieldLib for Int8Field global;

/// @notice The `int8` field codec, shared by every `int8` field of every table.
library Int8FieldLib {
  function load(Int8Field memory self) internal view returns (int8) {
    return int8(uint8(bytes1(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int8Field memory self, int8 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int8 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int8) {
    return int8(uint8(Bytes.getBytes1(staticData, offset)));
  }
}
