// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `int96` field of a record.
struct Int96Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Int96FieldLib for Int96Field global;

/// @notice The `int96` field codec, shared by every `int96` field of every table.
library Int96FieldLib {
  function load(Int96Field memory self) internal view returns (int96) {
    return int96(uint96(bytes12(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout))));
  }

  function save(Int96Field memory self, int96 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(int96 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (int96) {
    return int96(uint96(Bytes.getBytes12(staticData, offset)));
  }
}
