// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `uint120` field of a record.
struct Uint120Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint120FieldLib for Uint120Field global;

/// @notice The `uint120` field codec, shared by every `uint120` field of every table.
library Uint120FieldLib {
  function load(Uint120Field memory self) internal view returns (uint120) {
    return uint120(bytes15(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint120Field memory self, uint120 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint120 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint120) {
    return uint120(Bytes.getBytes15(staticData, offset));
  }
}
