// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `uint128` field of a record.
struct Uint128Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint128FieldLib for Uint128Field global;

/// @notice The `uint128` field codec, shared by every `uint128` field of every table.
library Uint128FieldLib {
  function load(Uint128Field memory self) internal view returns (uint128) {
    return uint128(bytes16(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint128Field memory self, uint128 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint128 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint128) {
    return uint128(Bytes.getBytes16(staticData, offset));
  }
}
