// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `uint240` field of a record.
struct Uint240Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint240FieldLib for Uint240Field global;

/// @notice The `uint240` field codec, shared by every `uint240` field of every table.
library Uint240FieldLib {
  function load(Uint240Field memory self) internal view returns (uint240) {
    return uint240(bytes30(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint240Field memory self, uint240 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint240 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint240) {
    return uint240(Bytes.getBytes30(staticData, offset));
  }
}
