// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `uint16` field of a record.
struct Uint16Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint16FieldLib for Uint16Field global;

/// @notice The `uint16` field codec, shared by every `uint16` field of every table.
library Uint16FieldLib {
  function load(Uint16Field memory self) internal view returns (uint16) {
    return uint16(bytes2(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint16Field memory self, uint16 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint16 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint16) {
    return uint16(Bytes.getBytes2(staticData, offset));
  }
}
