// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `uint232` field of a record.
struct Uint232Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint232FieldLib for Uint232Field global;

/// @notice The `uint232` field codec, shared by every `uint232` field of every table.
library Uint232FieldLib {
  function load(Uint232Field memory self) internal view returns (uint232) {
    return uint232(bytes29(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint232Field memory self, uint232 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint232 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint232) {
    return uint232(Bytes.getBytes29(staticData, offset));
  }
}
