// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `uint192` field of a record.
struct Uint192Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint192FieldLib for Uint192Field global;

/// @notice The `uint192` field codec, shared by every `uint192` field of every table.
library Uint192FieldLib {
  function load(Uint192Field memory self) internal view returns (uint192) {
    return uint192(bytes24(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint192Field memory self, uint192 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint192 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint192) {
    return uint192(Bytes.getBytes24(staticData, offset));
  }
}
