// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `uint72` field of a record.
struct Uint72Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint72FieldLib for Uint72Field global;

/// @notice The `uint72` field codec, shared by every `uint72` field of every table.
library Uint72FieldLib {
  function load(Uint72Field memory self) internal view returns (uint72) {
    return uint72(bytes9(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint72Field memory self, uint72 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint72 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint72) {
    return uint72(Bytes.getBytes9(staticData, offset));
  }
}
