// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `uint40` field of a record.
struct Uint40Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint40FieldLib for Uint40Field global;

/// @notice The `uint40` field codec, shared by every `uint40` field of every table.
library Uint40FieldLib {
  function load(Uint40Field memory self) internal view returns (uint40) {
    return uint40(bytes5(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint40Field memory self, uint40 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint40 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint40) {
    return uint40(Bytes.getBytes5(staticData, offset));
  }
}
