// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `uint168` field of a record.
struct Uint168Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint168FieldLib for Uint168Field global;

/// @notice The `uint168` field codec, shared by every `uint168` field of every table.
library Uint168FieldLib {
  function load(Uint168Field memory self) internal view returns (uint168) {
    return uint168(bytes21(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint168Field memory self, uint168 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint168 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint168) {
    return uint168(Bytes.getBytes21(staticData, offset));
  }
}
