// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `uint80` field of a record.
struct Uint80Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint80FieldLib for Uint80Field global;

/// @notice The `uint80` field codec, shared by every `uint80` field of every table.
library Uint80FieldLib {
  function load(Uint80Field memory self) internal view returns (uint80) {
    return uint80(bytes10(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint80Field memory self, uint80 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint80 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint80) {
    return uint80(Bytes.getBytes10(staticData, offset));
  }
}
