// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `uint56` field of a record.
struct Uint56Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint56FieldLib for Uint56Field global;

/// @notice The `uint56` field codec, shared by every `uint56` field of every table.
library Uint56FieldLib {
  function load(Uint56Field memory self) internal view returns (uint56) {
    return uint56(bytes7(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint56Field memory self, uint56 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint56 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint56) {
    return uint56(Bytes.getBytes7(staticData, offset));
  }
}
