// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `uint8` field of a record.
struct Uint8Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint8FieldLib for Uint8Field global;

/// @notice The `uint8` field codec, shared by every `uint8` field of every table.
library Uint8FieldLib {
  function load(Uint8Field memory self) internal view returns (uint8) {
    return uint8(bytes1(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint8Field memory self, uint8 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint8 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint8) {
    return uint8(Bytes.getBytes1(staticData, offset));
  }
}
