// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `uint200` field of a record.
struct Uint200Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint200FieldLib for Uint200Field global;

/// @notice The `uint200` field codec, shared by every `uint200` field of every table.
library Uint200FieldLib {
  function load(Uint200Field memory self) internal view returns (uint200) {
    return uint200(bytes25(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint200Field memory self, uint200 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint200 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint200) {
    return uint200(Bytes.getBytes25(staticData, offset));
  }
}
