// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `uint216` field of a record.
struct Uint216Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint216FieldLib for Uint216Field global;

/// @notice The `uint216` field codec, shared by every `uint216` field of every table.
library Uint216FieldLib {
  function load(Uint216Field memory self) internal view returns (uint216) {
    return uint216(bytes27(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint216Field memory self, uint216 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint216 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint216) {
    return uint216(Bytes.getBytes27(staticData, offset));
  }
}
