// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `uint48` field of a record.
struct Uint48Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint48FieldLib for Uint48Field global;

/// @notice The `uint48` field codec, shared by every `uint48` field of every table.
library Uint48FieldLib {
  function load(Uint48Field memory self) internal view returns (uint48) {
    return uint48(bytes6(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint48Field memory self, uint48 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint48 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint48) {
    return uint48(Bytes.getBytes6(staticData, offset));
  }
}
