// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { FieldLayout } from "../FieldLayout.sol";
import { Bytes } from "../Bytes.sol";

/// @notice A handle to one `uint152` field of a record.
struct Uint152Field {
  Record record;
  FieldLayout fieldLayout;
  uint8 index;
}

using Uint152FieldLib for Uint152Field global;

/// @notice The `uint152` field codec, shared by every `uint152` field of every table.
library Uint152FieldLib {
  function load(Uint152Field memory self) internal view returns (uint152) {
    return uint152(bytes19(StoreAccess.getStaticField(self.record, self.index, self.fieldLayout)));
  }

  function save(Uint152Field memory self, uint152 value) internal {
    StoreAccess.setStaticField(self.record, self.index, encode(value), self.fieldLayout);
  }

  function encode(uint152 value) internal pure returns (bytes memory) {
    return abi.encodePacked(value);
  }

  function decode(bytes memory staticData, uint256 offset) internal pure returns (uint152) {
    return uint152(Bytes.getBytes19(staticData, offset));
  }
}
