// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, StoreAccess } from "../Record.sol";
import { EncodedLengths } from "../EncodedLengths.sol";
import { SliceLib } from "../Slice.sol";
import { EncodeArray } from "../tightcoder/EncodeArray.sol";
import { DynamicRange } from "./_dynamic.sol";

/// @notice A handle to one `uint120[]` field of a record.
struct Uint120ArrayField {
  Record record;
  uint8 dynamicIndex;
}

using Uint120ArrayFieldLib for Uint120ArrayField global;

/// @notice The `uint120[]` field codec, shared by every `uint120[]` field of every table.
library Uint120ArrayFieldLib {
  uint256 constant _ELEMENT_SIZE = 15;

  function load(Uint120ArrayField memory self) internal view returns (uint120[] memory) {
    bytes memory blob = StoreAccess.getDynamicField(self.record, self.dynamicIndex);
    return SliceLib.getSubslice(blob, 0, blob.length).decodeArray_uint120();
  }

  function save(Uint120ArrayField memory self, uint120[] memory value) internal {
    StoreAccess.setDynamicField(self.record, self.dynamicIndex, EncodeArray.encode(value));
  }

  /// @notice Number of elements.
  function length(Uint120ArrayField memory self) internal view returns (uint256) {
    return StoreAccess.getDynamicFieldLength(self.record, self.dynamicIndex) / _ELEMENT_SIZE;
  }

  /// @notice Load one element by index.
  function load(Uint120ArrayField memory self, uint256 index) internal view returns (uint120) {
    bytes memory blob = StoreAccess.getDynamicFieldSlice(
      self.record,
      self.dynamicIndex,
      index * _ELEMENT_SIZE,
      (index + 1) * _ELEMENT_SIZE
    );
    return uint120(bytes15(blob));
  }

  /// @notice Overwrite one element by index.
  function save(Uint120ArrayField memory self, uint256 index, uint120 element) internal {
    StoreAccess.spliceDynamicData(
      self.record,
      self.dynamicIndex,
      uint40(index * _ELEMENT_SIZE),
      uint40(_ELEMENT_SIZE),
      abi.encodePacked(element)
    );
  }

  function push(Uint120ArrayField memory self, uint120 element) internal {
    StoreAccess.pushToDynamicField(self.record, self.dynamicIndex, abi.encodePacked(element));
  }

  function pop(Uint120ArrayField memory self) internal {
    StoreAccess.popFromDynamicField(self.record, self.dynamicIndex, _ELEMENT_SIZE);
  }

  function encode(uint120[] memory value) internal pure returns (bytes memory) {
    return EncodeArray.encode(value);
  }

  function byteLength(uint120[] memory value) internal pure returns (uint256) {
    return value.length * _ELEMENT_SIZE;
  }

  function decode(
    bytes memory dynamicData,
    EncodedLengths encodedLengths,
    uint8 dynamicIndex
  ) internal pure returns (uint120[] memory) {
    (uint256 start, uint256 end) = DynamicRange.range(encodedLengths, dynamicIndex);
    return SliceLib.getSubslice(dynamicData, start, end).decodeArray_uint120();
  }
}
