// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, RecordMethods } from "@latticexyz/store/src/v3/Record.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { Int32Field, Int32FieldLib } from "@latticexyz/store/src/v3/fields/Int32Field.sol";
import { StringField, StringFieldLib } from "@latticexyz/store/src/v3/fields/StringField.sol";
import { Uint32ArrayField, Uint32ArrayFieldLib } from "@latticexyz/store/src/v3/fields/Uint32ArrayField.sol";

struct PositionData {
  int32 x;
  int32 y;
  string name;
  uint32[] waypoints;
}

/// @notice The Position record at the given key, bound to the canonical table id.
function Position(address player) pure returns (PositionRecord memory) {
  bytes32[] memory keyTuple = new bytes32[](1);
  keyTuple[0] = bytes32(uint256(uint160(player)));
  return PositionRecord(Record(PositionRecordMethods._tableId, keyTuple, address(0)));
}

struct PositionRecord {
  Record record;
}

using PositionRecordMethods for PositionRecord global;

library PositionRecordMethods {
  ResourceId constant _tableId = ResourceId.wrap(0x74620000000000000000000000000000506f736974696f6e0000000000000000);
  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0008020204040000000000000000000000000000000000000000000000000000);
  Schema constant _keySchema = Schema.wrap(0x0014010061000000000000000000000000000000000000000000000000000000);
  Schema constant _valueSchema = Schema.wrap(0x000802022323c565000000000000000000000000000000000000000000000000);

  /// @notice Operate on a non-canonical table id (e.g. a module's namespaced instance).
  function at(PositionRecord memory self, ResourceId tableId) internal pure returns (PositionRecord memory) {
    self.record.tableId = tableId;
    return self;
  }

  /// @notice Declare this contract's own storage as the store (skips StoreSwitch inference).
  function own(PositionRecord memory self) internal view returns (PositionRecord memory) {
    self.record.store = address(this);
    return self;
  }

  /// @notice Declare an explicit store to read/write.
  function own(PositionRecord memory self, address store) internal pure returns (PositionRecord memory) {
    self.record.store = store;
    return self;
  }

  /// @notice Read the whole record and decode it into a memory struct.
  function load(PositionRecord memory self) internal view returns (PositionData memory) {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = RecordMethods.load(
      self.record
    );
    return _decode(staticData, encodedLengths, dynamicData);
  }

  /// @notice Encode and write the whole record.
  function save(PositionRecord memory self, PositionData memory data) internal {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = _encode(data);
    RecordMethods.save(self.record, staticData, encodedLengths, dynamicData);
  }

  /// @notice Delete the whole record.
  function destroy(PositionRecord memory self) internal {
    RecordMethods.destroy(self.record);
  }

  /// @notice Handle for the `x` field.
  function x(PositionRecord memory self) internal pure returns (Int32Field memory) {
    return Int32Field(self.record, _fieldLayout, 0);
  }

  /// @notice Handle for the `y` field.
  function y(PositionRecord memory self) internal pure returns (Int32Field memory) {
    return Int32Field(self.record, _fieldLayout, 1);
  }

  /// @notice Handle for the `name` field.
  function name(PositionRecord memory self) internal pure returns (StringField memory) {
    return StringField(self.record, 0);
  }

  /// @notice Handle for the `waypoints` field.
  function waypoints(PositionRecord memory self) internal pure returns (Uint32ArrayField memory) {
    return Uint32ArrayField(self.record, 1);
  }

  /// @notice Encode `PositionData` into the store's (static, lengths, dynamic) triple.
  function _encode(PositionData memory data) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory staticData = abi.encodePacked(Int32FieldLib.encode(data.x), Int32FieldLib.encode(data.y));

    EncodedLengths encodedLengths = EncodedLengthsLib.pack(
      StringFieldLib.byteLength(data.name),
      Uint32ArrayFieldLib.byteLength(data.waypoints)
    );
    bytes memory dynamicData = abi.encodePacked(
      StringFieldLib.encode(data.name),
      Uint32ArrayFieldLib.encode(data.waypoints)
    );
    return (staticData, encodedLengths, dynamicData);
  }

  /// @notice Decode the store's (static, lengths, dynamic) triple into `PositionData`.
  function _decode(
    bytes memory staticData,
    EncodedLengths encodedLengths,
    bytes memory dynamicData
  ) internal pure returns (PositionData memory data) {
    data.x = Int32FieldLib.decode(staticData, 0);
    data.y = Int32FieldLib.decode(staticData, 4);
    data.name = StringFieldLib.decode(dynamicData, encodedLengths, 0);
    data.waypoints = Uint32ArrayFieldLib.decode(dynamicData, encodedLengths, 1);
  }
}
