// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, RecordMethods } from "../../../src/Record.sol";
import { StoreSwitch } from "../../../src/StoreSwitch.sol";
import { ResourceId } from "../../../src/ResourceId.sol";
import { FieldLayout } from "../../../src/FieldLayout.sol";
import { Schema } from "../../../src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "../../../src/EncodedLengths.sol";

import { SliceLib } from "../../../src/Slice.sol";
import { DynamicRange } from "../../../src/fields/_dynamic.sol";
import { EncodeArray } from "../../../src/tightcoder/EncodeArray.sol";
import { Uint32ArrayField, Uint32ArrayFieldLib } from "../../../src/fields/Uint32ArrayField.sol";
import { StringField, StringFieldLib } from "../../../src/fields/StringField.sol";

import { MyId } from "../MyId.sol";

struct InventoryData {
  uint32[] items;
  string label;
}

/// @notice The Inventory record at the given key, bound to the canonical table id.
function Inventory(MyId owner) pure returns (InventoryRecord memory) {
  return InventoryRecord(Record(InventoryRecordMethods._tableId, InventoryRecordMethods._encodeKey(owner), address(0)));
}

struct InventoryRecord {
  Record record;
}

using InventoryRecordMethods for InventoryRecord global;

library InventoryRecordMethods {
  ResourceId constant _tableId = ResourceId.wrap(0x74620000000000000000000000000000496e76656e746f727900000000000000);
  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0000000200000000000000000000000000000000000000000000000000000000);
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  Schema constant _valueSchema = Schema.wrap(0x0000000265c50000000000000000000000000000000000000000000000000000);

  /// @notice Operate on a non-canonical table id (e.g. a module's namespaced instance).
  function at(InventoryRecord memory self, ResourceId tableId) internal pure returns (InventoryRecord memory) {
    self.record.tableId = tableId;
    return self;
  }

  /// @notice Declare this contract's own storage as the store (skips StoreSwitch inference).
  function own(InventoryRecord memory self) internal view returns (InventoryRecord memory) {
    self.record.store = address(this);
    return self;
  }

  /// @notice Declare an explicit store to read/write.
  function own(InventoryRecord memory self, address store) internal pure returns (InventoryRecord memory) {
    self.record.store = store;
    return self;
  }

  /// @notice Read the whole record and decode it into a memory struct.
  /// @dev Passes the table's constant `_fieldLayout`, skipping the store's layout lookup.
  function load(InventoryRecord memory self) internal view returns (InventoryData memory) {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = RecordMethods.load(
      self.record,
      _fieldLayout
    );
    return _decode(staticData, encodedLengths, dynamicData);
  }

  /// @notice Encode and write the whole record.
  function save(InventoryRecord memory self, InventoryData memory data) internal {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = _encode(data);
    RecordMethods.save(self.record, staticData, encodedLengths, dynamicData, _fieldLayout);
  }

  /// @notice Delete the whole record.
  function destroy(InventoryRecord memory self) internal {
    RecordMethods.destroy(self.record, _fieldLayout);
  }

  /// @notice Handle for the `items` field.
  function items(InventoryRecord memory self) internal pure returns (Uint32ArrayField memory) {
    return Uint32ArrayField(self.record, 0);
  }

  /// @notice Handle for the `label` field.
  function label(InventoryRecord memory self) internal pure returns (StringField memory) {
    return StringField(self.record, 1);
  }

  /// @notice Encode the key tuple — a primitive for composing direct store calls.
  function _encodeKey(MyId owner) internal pure returns (bytes32[] memory keyTuple) {
    keyTuple = new bytes32[](1);
    keyTuple[0] = MyId.unwrap(owner);
  }

  /// @notice Recover the typed key from a raw keyTuple (e.g. inside a store hook).
  function _decodeKey(bytes32[] memory keyTuple) internal pure returns (MyId owner) {
    owner = MyId.wrap(keyTuple[0]);
  }

  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "owner";
  }

  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "items";
    fieldNames[1] = "label";
  }

  /// @notice Register this table. Use the low-level `StoreCore.registerTable` with the
  ///         `_*` constants + name getters to register against a specific store.
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /// @notice Encode `InventoryData` into the store's (static, lengths, dynamic) triple.
  function _encode(InventoryData memory data) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory staticData = abi.encodePacked();

    EncodedLengths encodedLengths = EncodedLengthsLib.pack(data.items.length * 4, bytes(data.label).length);
    bytes memory dynamicData = abi.encodePacked(EncodeArray.encode(data.items), bytes(data.label));
    return (staticData, encodedLengths, dynamicData);
  }

  /// @notice Decode the store's (static, lengths, dynamic) triple into `InventoryData`.
  function _decode(
    bytes memory staticData,
    EncodedLengths encodedLengths,
    bytes memory dynamicData
  ) internal pure returns (InventoryData memory data) {
    (uint256 _start0, uint256 _end0) = DynamicRange.range(encodedLengths, 0);
    data.items = SliceLib.getSubslice(dynamicData, _start0, _end0).decodeArray_uint32();

    (uint256 _start1, uint256 _end1) = DynamicRange.range(encodedLengths, 1);
    data.label = string(SliceLib.getSubslice(dynamicData, _start1, _end1).toBytes());
  }
}
