// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, RecordMethods } from "../../../src/v3/Record.sol";
import { StoreSwitch } from "../../../src/StoreSwitch.sol";
import { ResourceId } from "../../../src/ResourceId.sol";
import { FieldLayout } from "../../../src/FieldLayout.sol";
import { Schema } from "../../../src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "../../../src/EncodedLengths.sol";
import { Bytes21ArrayField, Bytes21ArrayFieldLib } from "../../../src/v3/fields/Bytes21ArrayField.sol";

import { ResourceId } from "../../../src/ResourceId.sol";

struct HooksData {
  bytes21[] hooks;
}

/// @notice The Hooks record at the given key, bound to the canonical table id.
function Hooks(ResourceId resourceId) pure returns (HooksRecord memory) {
  return HooksRecord(Record(HooksRecordMethods._tableId, HooksRecordMethods._encodeKey(resourceId), address(0)));
}

struct HooksRecord {
  Record record;
}

using HooksRecordMethods for HooksRecord global;

library HooksRecordMethods {
  ResourceId constant _tableId = ResourceId.wrap(0x746273746f7265000000000000000000486f6f6b730000000000000000000000);
  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0000000100000000000000000000000000000000000000000000000000000000);
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  Schema constant _valueSchema = Schema.wrap(0x00000001b6000000000000000000000000000000000000000000000000000000);

  /// @notice Operate on a non-canonical table id (e.g. a module's namespaced instance).
  function at(HooksRecord memory self, ResourceId tableId) internal pure returns (HooksRecord memory) {
    self.record.tableId = tableId;
    return self;
  }

  /// @notice Declare this contract's own storage as the store (skips StoreSwitch inference).
  function own(HooksRecord memory self) internal view returns (HooksRecord memory) {
    self.record.store = address(this);
    return self;
  }

  /// @notice Declare an explicit store to read/write.
  function own(HooksRecord memory self, address store) internal pure returns (HooksRecord memory) {
    self.record.store = store;
    return self;
  }

  /// @notice Read the whole record and decode it into a memory struct.
  function load(HooksRecord memory self) internal view returns (HooksData memory) {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = RecordMethods.load(
      self.record
    );
    return _decode(staticData, encodedLengths, dynamicData);
  }

  /// @notice Encode and write the whole record.
  function save(HooksRecord memory self, HooksData memory data) internal {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = _encode(data);
    RecordMethods.save(self.record, staticData, encodedLengths, dynamicData);
  }

  /// @notice Delete the whole record.
  function destroy(HooksRecord memory self) internal {
    RecordMethods.destroy(self.record);
  }

  /// @notice Handle for the `hooks` field.
  function hooks(HooksRecord memory self) internal pure returns (Bytes21ArrayField memory) {
    return Bytes21ArrayField(self.record, 0);
  }

  /// @notice Encode the key tuple — a primitive for composing direct store calls.
  function _encodeKey(ResourceId resourceId) internal pure returns (bytes32[] memory keyTuple) {
    keyTuple = new bytes32[](1);
    keyTuple[0] = ResourceId.unwrap(resourceId);
  }

  /// @notice Recover the typed key from a raw keyTuple (e.g. inside a store hook).
  function _decodeKey(bytes32[] memory keyTuple) internal pure returns (ResourceId resourceId) {
    resourceId = ResourceId.wrap(keyTuple[0]);
  }

  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "resourceId";
  }

  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](1);
    fieldNames[0] = "hooks";
  }

  /// @notice Register this table. Use the low-level `StoreCore.registerTable` with the
  ///         `_*` constants + name getters to register against a specific store.
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /// @notice Encode `HooksData` into the store's (static, lengths, dynamic) triple.
  function _encode(HooksData memory data) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory staticData = abi.encodePacked();

    EncodedLengths encodedLengths = EncodedLengthsLib.pack(Bytes21ArrayFieldLib.byteLength(data.hooks));
    bytes memory dynamicData = abi.encodePacked(Bytes21ArrayFieldLib.encode(data.hooks));
    return (staticData, encodedLengths, dynamicData);
  }

  /// @notice Decode the store's (static, lengths, dynamic) triple into `HooksData`.
  function _decode(
    bytes memory staticData,
    EncodedLengths encodedLengths,
    bytes memory dynamicData
  ) internal pure returns (HooksData memory data) {
    data.hooks = Bytes21ArrayFieldLib.decode(dynamicData, encodedLengths, 0);
  }
}
