// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Record, RecordMethods } from "../../../src/v3/Record.sol";
import { StoreSwitch } from "../../../src/StoreSwitch.sol";
import { ResourceId } from "../../../src/ResourceId.sol";
import { FieldLayout } from "../../../src/FieldLayout.sol";
import { Schema } from "../../../src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "../../../src/EncodedLengths.sol";
import { BoolField, BoolFieldLib } from "../../../src/v3/fields/BoolField.sol";

import { ResourceId } from "../../../src/ResourceId.sol";

struct ResourceIdsData {
  bool exists;
}

/// @notice The ResourceIds record at the given key, bound to the canonical table id.
function ResourceIds(ResourceId resourceId) pure returns (ResourceIdsRecord memory) {
  return
    ResourceIdsRecord(
      Record(ResourceIdsRecordMethods._tableId, ResourceIdsRecordMethods._encodeKey(resourceId), address(0))
    );
}

struct ResourceIdsRecord {
  Record record;
}

using ResourceIdsRecordMethods for ResourceIdsRecord global;

library ResourceIdsRecordMethods {
  ResourceId constant _tableId = ResourceId.wrap(0x746273746f72650000000000000000005265736f757263654964730000000000);
  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0001010001000000000000000000000000000000000000000000000000000000);
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  Schema constant _valueSchema = Schema.wrap(0x0001010060000000000000000000000000000000000000000000000000000000);

  /// @notice Operate on a non-canonical table id (e.g. a module's namespaced instance).
  function at(ResourceIdsRecord memory self, ResourceId tableId) internal pure returns (ResourceIdsRecord memory) {
    self.record.tableId = tableId;
    return self;
  }

  /// @notice Declare this contract's own storage as the store (skips StoreSwitch inference).
  function own(ResourceIdsRecord memory self) internal view returns (ResourceIdsRecord memory) {
    self.record.store = address(this);
    return self;
  }

  /// @notice Declare an explicit store to read/write.
  function own(ResourceIdsRecord memory self, address store) internal pure returns (ResourceIdsRecord memory) {
    self.record.store = store;
    return self;
  }

  /// @notice Read the whole record and decode it into a memory struct.
  function load(ResourceIdsRecord memory self) internal view returns (ResourceIdsData memory) {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = RecordMethods.load(
      self.record
    );
    return _decode(staticData, encodedLengths, dynamicData);
  }

  /// @notice Encode and write the whole record.
  function save(ResourceIdsRecord memory self, ResourceIdsData memory data) internal {
    (bytes memory staticData, EncodedLengths encodedLengths, bytes memory dynamicData) = _encode(data);
    RecordMethods.save(self.record, staticData, encodedLengths, dynamicData);
  }

  /// @notice Delete the whole record.
  function destroy(ResourceIdsRecord memory self) internal {
    RecordMethods.destroy(self.record);
  }

  /// @notice Handle for the `exists` field.
  function exists(ResourceIdsRecord memory self) internal pure returns (BoolField memory) {
    return BoolField(self.record, _fieldLayout, 0);
  }

  /// @notice Encode the key tuple — a primitive for composing direct store calls.
  function _encodeKey(ResourceId resourceId) internal pure returns (bytes32[] memory keyTuple) {
    keyTuple = new bytes32[](1);
    keyTuple[0] = ResourceId.unwrap(resourceId);
  }

  /// @notice Recover the typed key from a raw keyTuple (e.g. inside a store hook).
  function _decodeKey(bytes32[] memory keyTuple) internal pure returns (ResourceId resourceId) {
    resourceId = ResourceId.wrap(keyTuple[0]);
  }

  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "resourceId";
  }

  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](1);
    fieldNames[0] = "exists";
  }

  /// @notice Register this table. Use the low-level `StoreCore.registerTable` with the
  ///         `_*` constants + name getters to register against a specific store.
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /// @notice Encode `ResourceIdsData` into the store's (static, lengths, dynamic) triple.
  function _encode(ResourceIdsData memory data) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory staticData = abi.encodePacked(BoolFieldLib.encode(data.exists));
    return (staticData, EncodedLengths.wrap(bytes32(0)), new bytes(0));
  }

  /// @notice Decode the store's (static, lengths, dynamic) triple into `ResourceIdsData`.
  function _decode(
    bytes memory staticData,
    EncodedLengths encodedLengths,
    bytes memory dynamicData
  ) internal pure returns (ResourceIdsData memory data) {
    data.exists = BoolFieldLib.decode(staticData, 0);
  }
}
